//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsitec.Data.Platform.Directories.Version.Version {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:directories/version/v1/version", ConfigurationName="Directories.Version.Version.VersionSoap")]
    public interface VersionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/version/v1/version/GetVersionInfos", ReplyAction="*")]
        string GetVersionInfos(string wsInfoParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/version/v1/version/GetServiceStatus", ReplyAction="*")]
        string GetServiceStatus(string wsInfoParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/version/v1/version/Version", ReplyAction="*")]
        string Version();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VersionSoapChannel : Epsitec.Data.Platform.Directories.Version.Version.VersionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VersionSoapClient : System.ServiceModel.ClientBase<Epsitec.Data.Platform.Directories.Version.Version.VersionSoap>, Epsitec.Data.Platform.Directories.Version.Version.VersionSoap {
        
        public VersionSoapClient() {
        }
        
        public VersionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VersionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersionInfos(string wsInfoParam) {
            return base.Channel.GetVersionInfos(wsInfoParam);
        }
        
        public string GetServiceStatus(string wsInfoParam) {
            return base.Channel.GetServiceStatus(wsInfoParam);
        }
        
        public string Version() {
            return base.Channel.Version();
        }
    }
}
