//	Automatically generated by ResGenerator, on 24.05.2007
//	Do not edit manually.

namespace Epsitec.Common.Support
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		public static class Types
		{
			public static readonly Epsitec.Common.Types.StructuredType Field = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 36));
			public static readonly Epsitec.Common.Types.CollectionType FieldCollection = (Epsitec.Common.Types.CollectionType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 35));
			public static readonly Epsitec.Common.Types.StructuredType ResourceBase = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 43));
			public static readonly Epsitec.Common.Types.StructuredType ResourceCaption = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 6));
			public static readonly Epsitec.Common.Types.StructuredType ResourceCommand = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 16));
			public static readonly Epsitec.Common.Types.StructuredType ResourceEntity = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 17));
			public static readonly Epsitec.Common.Types.StructuredType ResourceString = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 7));
			public static readonly Epsitec.Common.Types.StructuredType Shortcut = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 26));
			public static readonly Epsitec.Common.Types.CollectionType ShortcutCollection = (Epsitec.Common.Types.CollectionType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 25));
			public static readonly Epsitec.Common.Types.CollectionType StringCollection = (Epsitec.Common.Types.CollectionType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 15));
		}
		
		public static class Fields
		{
			public static class Field
			{
				public static readonly Epsitec.Common.Support.Druid Caption = Epsitec.Common.Support.Druid.FromLong (_moduleId, 38);
				public static readonly Epsitec.Common.Support.Druid Membership = Epsitec.Common.Support.Druid.FromLong (_moduleId, 3);
				public static readonly Epsitec.Common.Support.Druid Relation = Epsitec.Common.Support.Druid.FromLong (_moduleId, 39);
				public static readonly Epsitec.Common.Support.Druid SourceField = Epsitec.Common.Support.Druid.FromLong (_moduleId, 40);
				public static readonly Epsitec.Common.Support.Druid Type = Epsitec.Common.Support.Druid.FromLong (_moduleId, 37);
			}
			
			public static class ResourceBase
			{
				public static readonly Epsitec.Common.Support.Druid Comment = Epsitec.Common.Support.Druid.FromLong (_moduleId, 10);
				public static readonly Epsitec.Common.Support.Druid ModificationId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 41);
			}
			
			public static class ResourceCaption
			{
				public static readonly Epsitec.Common.Support.Druid Description = Epsitec.Common.Support.Druid.FromLong (_moduleId, 12);
				public static readonly Epsitec.Common.Support.Druid Icon = Epsitec.Common.Support.Druid.FromLong (_moduleId, 13);
				public static readonly Epsitec.Common.Support.Druid Labels = Epsitec.Common.Support.Druid.FromLong (_moduleId, 11);
			}
			
			public static class ResourceCommand
			{
				public static readonly Epsitec.Common.Support.Druid DefaultParameter = Epsitec.Common.Support.Druid.FromLong (_moduleId, 22);
				public static readonly Epsitec.Common.Support.Druid Group = Epsitec.Common.Support.Druid.FromLong (_moduleId, 42);
				public static readonly Epsitec.Common.Support.Druid Shortcuts = Epsitec.Common.Support.Druid.FromLong (_moduleId, 24);
				public static readonly Epsitec.Common.Support.Druid Statefull = Epsitec.Common.Support.Druid.FromLong (_moduleId, 23);
			}
			
			public static class ResourceEntity
			{
				public static readonly Epsitec.Common.Support.Druid DefaultController = Epsitec.Common.Support.Druid.FromLong (_moduleId, 32);
				public static readonly Epsitec.Common.Support.Druid Fields = Epsitec.Common.Support.Druid.FromLong (_moduleId, 34);
				public static readonly Epsitec.Common.Support.Druid Nullable = Epsitec.Common.Support.Druid.FromLong (_moduleId, 33);
			}
			
			public static class ResourceString
			{
				public static readonly Epsitec.Common.Support.Druid Text = Epsitec.Common.Support.Druid.FromLong (_moduleId, 8);
			}
			
			public static class Shortcut
			{
				public static readonly Epsitec.Common.Support.Druid KeyCode = Epsitec.Common.Support.Druid.FromLong (_moduleId, 27);
			}
		}
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static class Image
			{
				public static string Description { get { return Epsitec.Common.Support.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (0)); } }
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}
		
		//	Code mapping for 'Panel' resources
		
		static Res()
		{
			Res.Initialize (typeof (Res), "Common.Support");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 7;
	}
}
