//	Automatically generated by ResGenerator, on 26.06.2007
//	Do not edit manually.

namespace Epsitec.Common.Support
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		public static class Types
		{
			public static readonly Epsitec.Common.Types.StructuredType EnumValue = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 70));
			public static readonly Epsitec.Common.Types.StructuredType Field = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 36));
			public static readonly Epsitec.Common.Types.StructuredType ResourceBase = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 43));
			public static readonly Epsitec.Common.Types.StructuredType ResourceBaseType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 5));
			public static readonly Epsitec.Common.Types.StructuredType ResourceBinaryType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 64));
			public static readonly Epsitec.Common.Types.StructuredType ResourceCaption = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 6));
			public static readonly Epsitec.Common.Types.StructuredType ResourceCollectionType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 67));
			public static readonly Epsitec.Common.Types.StructuredType ResourceCommand = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 16));
			public static readonly Epsitec.Common.Types.StructuredType ResourceDateTimeType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 48));
			public static readonly Epsitec.Common.Types.StructuredType ResourceEnumType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 69));
			public static readonly Epsitec.Common.Types.StructuredType ResourceNumericType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 47));
			public static readonly Epsitec.Common.Types.StructuredType ResourceOtherType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 68));
			public static readonly Epsitec.Common.Types.StructuredType ResourceString = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 7));
			public static readonly Epsitec.Common.Types.StructuredType ResourceStringType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 49));
			public static readonly Epsitec.Common.Types.StructuredType ResourceStructuredType = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 17));
			public static readonly Epsitec.Common.Types.StructuredType Shortcut = (Epsitec.Common.Types.StructuredType) Epsitec.Common.Types.TypeRosetta.CreateTypeObject (Epsitec.Common.Support.Druid.FromLong (_moduleId, 26));
		}
		
		public static class Fields
		{
			public static class EnumValue
			{
				public static readonly Epsitec.Common.Support.Druid CaptionId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 74);
			}
			
			public static class Field
			{
				public static readonly Epsitec.Common.Support.Druid Caption = Epsitec.Common.Support.Druid.FromLong (_moduleId, 46);
				public static readonly Epsitec.Common.Support.Druid CaptionId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 38);
				public static readonly Epsitec.Common.Support.Druid DefiningTypeId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 80);
				public static readonly Epsitec.Common.Support.Druid Expression = Epsitec.Common.Support.Druid.FromLong (_moduleId, 78);
				public static readonly Epsitec.Common.Support.Druid Membership = Epsitec.Common.Support.Druid.FromLong (_moduleId, 3);
				public static readonly Epsitec.Common.Support.Druid Relation = Epsitec.Common.Support.Druid.FromLong (_moduleId, 39);
				public static readonly Epsitec.Common.Support.Druid Source = Epsitec.Common.Support.Druid.FromLong (_moduleId, 77);
				public static readonly Epsitec.Common.Support.Druid TypeId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 37);
			}
			
			public static class ResourceBase
			{
				public static readonly Epsitec.Common.Support.Druid Comment = Epsitec.Common.Support.Druid.FromLong (_moduleId, 10);
				public static readonly Epsitec.Common.Support.Druid ModificationId = Epsitec.Common.Support.Druid.FromLong (_moduleId, 41);
			}
			
			public static class ResourceBaseType
			{
				public static readonly Epsitec.Common.Support.Druid DefaultController = Epsitec.Common.Support.Druid.FromLong (_moduleId, 32);
				public static readonly Epsitec.Common.Support.Druid DefaultControllerParameter = Epsitec.Common.Support.Druid.FromLong (_moduleId, 75);
				public static readonly Epsitec.Common.Support.Druid Nullable = Epsitec.Common.Support.Druid.FromLong (_moduleId, 33);
				public static readonly Epsitec.Common.Support.Druid TypeCode = Epsitec.Common.Support.Druid.FromLong (_moduleId, 66);
			}
			
			public static class ResourceBinaryType
			{
				public static readonly Epsitec.Common.Support.Druid MimeType = Epsitec.Common.Support.Druid.FromLong (_moduleId, 65);
			}
			
			public static class ResourceCaption
			{
				public static readonly Epsitec.Common.Support.Druid Description = Epsitec.Common.Support.Druid.FromLong (_moduleId, 12);
				public static readonly Epsitec.Common.Support.Druid Icon = Epsitec.Common.Support.Druid.FromLong (_moduleId, 13);
				public static readonly Epsitec.Common.Support.Druid Labels = Epsitec.Common.Support.Druid.FromLong (_moduleId, 11);
			}
			
			public static class ResourceCollectionType
			{
				public static readonly Epsitec.Common.Support.Druid ItemType = Epsitec.Common.Support.Druid.FromLong (_moduleId, 72);
			}
			
			public static class ResourceCommand
			{
				public static readonly Epsitec.Common.Support.Druid DefaultParameter = Epsitec.Common.Support.Druid.FromLong (_moduleId, 22);
				public static readonly Epsitec.Common.Support.Druid Group = Epsitec.Common.Support.Druid.FromLong (_moduleId, 42);
				public static readonly Epsitec.Common.Support.Druid Shortcuts = Epsitec.Common.Support.Druid.FromLong (_moduleId, 24);
				public static readonly Epsitec.Common.Support.Druid Statefull = Epsitec.Common.Support.Druid.FromLong (_moduleId, 23);
			}
			
			public static class ResourceDateTimeType
			{
				public static readonly Epsitec.Common.Support.Druid DateStep = Epsitec.Common.Support.Druid.FromLong (_moduleId, 60);
				public static readonly Epsitec.Common.Support.Druid MaximumDate = Epsitec.Common.Support.Druid.FromLong (_moduleId, 56);
				public static readonly Epsitec.Common.Support.Druid MaximumTime = Epsitec.Common.Support.Druid.FromLong (_moduleId, 58);
				public static readonly Epsitec.Common.Support.Druid MinimumDate = Epsitec.Common.Support.Druid.FromLong (_moduleId, 55);
				public static readonly Epsitec.Common.Support.Druid MinimumTime = Epsitec.Common.Support.Druid.FromLong (_moduleId, 57);
				public static readonly Epsitec.Common.Support.Druid Resolution = Epsitec.Common.Support.Druid.FromLong (_moduleId, 54);
				public static readonly Epsitec.Common.Support.Druid TimeStep = Epsitec.Common.Support.Druid.FromLong (_moduleId, 59);
			}
			
			public static class ResourceEnumType
			{
				public static readonly Epsitec.Common.Support.Druid SystemType = Epsitec.Common.Support.Druid.FromLong (_moduleId, 76);
				public static readonly Epsitec.Common.Support.Druid Values = Epsitec.Common.Support.Druid.FromLong (_moduleId, 73);
			}
			
			public static class ResourceNumericType
			{
				public static readonly Epsitec.Common.Support.Druid LargeStep = Epsitec.Common.Support.Druid.FromLong (_moduleId, 53);
				public static readonly Epsitec.Common.Support.Druid PreferredRange = Epsitec.Common.Support.Druid.FromLong (_moduleId, 51);
				public static readonly Epsitec.Common.Support.Druid Range = Epsitec.Common.Support.Druid.FromLong (_moduleId, 50);
				public static readonly Epsitec.Common.Support.Druid SmallStep = Epsitec.Common.Support.Druid.FromLong (_moduleId, 52);
			}
			
			public static class ResourceOtherType
			{
				public static readonly Epsitec.Common.Support.Druid SystemType = Epsitec.Common.Support.Druid.FromLong (_moduleId, 71);
			}
			
			public static class ResourceString
			{
				public static readonly Epsitec.Common.Support.Druid Text = Epsitec.Common.Support.Druid.FromLong (_moduleId, 8);
			}
			
			public static class ResourceStringType
			{
				public static readonly Epsitec.Common.Support.Druid MaximumLength = Epsitec.Common.Support.Druid.FromLong (_moduleId, 62);
				public static readonly Epsitec.Common.Support.Druid MinimumLength = Epsitec.Common.Support.Druid.FromLong (_moduleId, 61);
				public static readonly Epsitec.Common.Support.Druid UseMultilingualStorage = Epsitec.Common.Support.Druid.FromLong (_moduleId, 63);
			}
			
			public static class ResourceStructuredType
			{
				public static readonly Epsitec.Common.Support.Druid BaseType = Epsitec.Common.Support.Druid.FromLong (_moduleId, 45);
				public static readonly Epsitec.Common.Support.Druid Class = Epsitec.Common.Support.Druid.FromLong (_moduleId, 44);
				public static readonly Epsitec.Common.Support.Druid Fields = Epsitec.Common.Support.Druid.FromLong (_moduleId, 34);
				public static readonly Epsitec.Common.Support.Druid InterfaceIds = Epsitec.Common.Support.Druid.FromLong (_moduleId, 81);
				public static readonly Epsitec.Common.Support.Druid SerializedDesignerLayouts = Epsitec.Common.Support.Druid.FromLong (_moduleId, 79);
			}
			
			public static class Shortcut
			{
				public static readonly Epsitec.Common.Support.Druid KeyCode = Epsitec.Common.Support.Druid.FromLong (_moduleId, 27);
			}
		}
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static class Image
			{
				public static string Description { get { return Epsitec.Common.Support.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (0)); } }
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}
		
		//	Code mapping for 'Panel' resources
		
		static Res()
		{
			Res.Initialize (typeof (Res), "Common.Support");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 7;
	}
}
