//	Automatically generated by ResGenerator, on 24.09.2007
//	Do not edit manually.

namespace Epsitec.Common.Support
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		public static class Captions
		{
			public static global::Epsitec.Common.Types.Caption TestCaption1 { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 5)); } }
			public static global::Epsitec.Common.Types.Caption TestCaption2 { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 6)); } }
			public static global::Epsitec.Common.Types.Caption TestCaption3 { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 8)); } }
			
		}
		
		public static class Types
		{
			public static readonly global::Epsitec.Common.Types.StructuredType EnumValue = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 70));
			public static readonly global::Epsitec.Common.Types.StructuredType Field = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 36));
			public static readonly global::Epsitec.Common.Types.StructuredType InterfaceId = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 9));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceBase = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 43));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceBaseType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 5));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceBinaryType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 64));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceCaption = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 6));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceCollectionType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 67));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceCommand = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 16));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceDateTimeType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 48));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceEnumType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 69));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceNumericType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 47));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceOtherType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 68));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourcePanel = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 14));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceString = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 7));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceStringType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 49));
			public static readonly global::Epsitec.Common.Types.StructuredType ResourceStructuredType = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 17));
			public static readonly global::Epsitec.Common.Types.StructuredType Shortcut = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 26));
			public static readonly global::Epsitec.Common.Types.StructuredType TestInterface = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 82));
			public static readonly global::Epsitec.Common.Types.StructuredType TestInterfaceUser = (global::Epsitec.Common.Types.StructuredType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 3));
		}
		
		public static class Fields
		{
			public static class EnumValue
			{
				public static readonly global::Epsitec.Common.Support.Druid CaptionId = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 74);
				public static readonly global::Epsitec.Common.Support.Druid CultureMapSource = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 13);
			}
			
			public static class Field
			{
				public static readonly global::Epsitec.Common.Support.Druid Caption = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 46);
				public static readonly global::Epsitec.Common.Support.Druid CaptionId = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 38);
				public static readonly global::Epsitec.Common.Support.Druid CultureMapSource = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 11);
				public static readonly global::Epsitec.Common.Support.Druid DefiningTypeId = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 80);
				public static readonly global::Epsitec.Common.Support.Druid Expression = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 78);
				public static readonly global::Epsitec.Common.Support.Druid Membership = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 3);
				public static readonly global::Epsitec.Common.Support.Druid Options = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 1);
				public static readonly global::Epsitec.Common.Support.Druid Relation = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 39);
				public static readonly global::Epsitec.Common.Support.Druid Source = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 77);
				public static readonly global::Epsitec.Common.Support.Druid TypeId = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 37);
			}
			
			public static class InterfaceId
			{
				public static readonly global::Epsitec.Common.Support.Druid CaptionId = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 10);
				public static readonly global::Epsitec.Common.Support.Druid CultureMapSource = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 12);
			}
			
			public static class ResourceBase
			{
				public static readonly global::Epsitec.Common.Support.Druid Comment = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 10);
				public static readonly global::Epsitec.Common.Support.Druid ModificationId = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 41);
			}
			
			public static class ResourceBaseType
			{
				public static readonly global::Epsitec.Common.Support.Druid DefaultController = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 32);
				public static readonly global::Epsitec.Common.Support.Druid DefaultControllerParameter = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 75);
				public static readonly global::Epsitec.Common.Support.Druid Nullable = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 33);
				public static readonly global::Epsitec.Common.Support.Druid TypeCode = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 66);
			}
			
			public static class ResourceBinaryType
			{
				public static readonly global::Epsitec.Common.Support.Druid MimeType = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 65);
			}
			
			public static class ResourceCaption
			{
				public static readonly global::Epsitec.Common.Support.Druid Description = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 12);
				public static readonly global::Epsitec.Common.Support.Druid Icon = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 13);
				public static readonly global::Epsitec.Common.Support.Druid Labels = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 11);
			}
			
			public static class ResourceCollectionType
			{
				public static readonly global::Epsitec.Common.Support.Druid ItemType = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 72);
			}
			
			public static class ResourceCommand
			{
				public static readonly global::Epsitec.Common.Support.Druid DefaultParameter = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 22);
				public static readonly global::Epsitec.Common.Support.Druid Group = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 42);
				public static readonly global::Epsitec.Common.Support.Druid Shortcuts = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 24);
				public static readonly global::Epsitec.Common.Support.Druid Statefull = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 23);
			}
			
			public static class ResourceDateTimeType
			{
				public static readonly global::Epsitec.Common.Support.Druid DateStep = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 60);
				public static readonly global::Epsitec.Common.Support.Druid MaximumDate = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 56);
				public static readonly global::Epsitec.Common.Support.Druid MaximumTime = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 58);
				public static readonly global::Epsitec.Common.Support.Druid MinimumDate = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 55);
				public static readonly global::Epsitec.Common.Support.Druid MinimumTime = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 57);
				public static readonly global::Epsitec.Common.Support.Druid Resolution = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 54);
				public static readonly global::Epsitec.Common.Support.Druid TimeStep = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 59);
			}
			
			public static class ResourceEnumType
			{
				public static readonly global::Epsitec.Common.Support.Druid SystemType = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 76);
				public static readonly global::Epsitec.Common.Support.Druid Values = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 73);
			}
			
			public static class ResourceNumericType
			{
				public static readonly global::Epsitec.Common.Support.Druid LargeStep = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 53);
				public static readonly global::Epsitec.Common.Support.Druid PreferredRange = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 51);
				public static readonly global::Epsitec.Common.Support.Druid Range = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 50);
				public static readonly global::Epsitec.Common.Support.Druid SmallStep = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 52);
			}
			
			public static class ResourceOtherType
			{
				public static readonly global::Epsitec.Common.Support.Druid SystemType = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 71);
			}
			
			public static class ResourcePanel
			{
				public static readonly global::Epsitec.Common.Support.Druid Bundle = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 15);
				public static readonly global::Epsitec.Common.Support.Druid DefaultSize = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 17);
				public static readonly global::Epsitec.Common.Support.Druid XmlSource = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 16);
			}
			
			public static class ResourceString
			{
				public static readonly global::Epsitec.Common.Support.Druid Text = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 8);
			}
			
			public static class ResourceStringType
			{
				public static readonly global::Epsitec.Common.Support.Druid MaximumLength = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 62);
				public static readonly global::Epsitec.Common.Support.Druid MinimumLength = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 61);
				public static readonly global::Epsitec.Common.Support.Druid UseMultilingualStorage = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 63);
			}
			
			public static class ResourceStructuredType
			{
				public static readonly global::Epsitec.Common.Support.Druid BaseType = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 45);
				public static readonly global::Epsitec.Common.Support.Druid Class = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 44);
				public static readonly global::Epsitec.Common.Support.Druid Fields = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 34);
				public static readonly global::Epsitec.Common.Support.Druid InterfaceIds = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 81);
				public static readonly global::Epsitec.Common.Support.Druid SerializedDesignerLayouts = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 79);
			}
			
			public static class Shortcut
			{
				public static readonly global::Epsitec.Common.Support.Druid KeyCode = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 27);
			}
			
			public static class TestInterface
			{
				public static readonly global::Epsitec.Common.Support.Druid Name = new global::Epsitec.Common.Support.Druid (_moduleId, 0, 83);
				public static readonly global::Epsitec.Common.Support.Druid Resource = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 2);
			}
			
			public static class TestInterfaceUser
			{
				public static readonly global::Epsitec.Common.Support.Druid Extension1 = new global::Epsitec.Common.Support.Druid (_moduleId, 1, 4);
			}
		}
		
		//	Code mapping for 'Panel' resources
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static string Author { get { return global::Epsitec.Common.Support.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (1)); } }
			public static string CopyrightHolder { get { return global::Epsitec.Common.Support.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (3)); } }
			public static class Image
			{
				public static string Description { get { return global::Epsitec.Common.Support.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (0)); } }
			}
			
			public static string Null { get { return global::Epsitec.Common.Support.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (2)); } }
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(global::Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static global::Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}
		
		static Res()
		{
			Res.Initialize (typeof (Res), "Common.Support");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new global::Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static global::Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static global::Epsitec.Common.Support.ResourceManager _manager = global::Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 7;
	}
}
