<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="en">
  <data id="01">&lt;s:data id="_0" f:Description="[4002]" f:Labels="{Collection {Text '[4003]'}, {Text '[4004]'}}" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Description="Pattern angle expressed in degrees." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Pattern angle'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Description="Quality coefficient." f:Labels="{Collection {Text 'Q'}}" /&gt;</data>
  <data id="04">&lt;s:data id="_0" f:Description="[4005]" f:Labels="{Collection {Text 'Text'}}" /&gt;</data>
  <data id="05">&lt;s:data id="_0" f:Name="OneOfThree" f:Description="One of Three" /&gt;</data>
  <data id="06">&lt;s:data id="_0" f:Name="None" f:Description="None" /&gt;</data>
  <data id="07">&lt;s:data id="_0" f:Name="First" f:Description="1st choice" /&gt;</data>
  <data id="08">&lt;s:data id="_0" f:Name="Second" f:Description="2nd choice" /&gt;</data>
  <data id="09">&lt;s:data id="_0" f:Name="Third" f:Description="3rd choice" /&gt;</data>
  <data id="0A">&lt;s:data id="_0" f:Description="Borrowed Text" /&gt;</data>
  <data id="0B">&lt;s:data id="_0" f:Name="Default" f:Description="Default color palette" f:Labels="{Collection {Text 'Default palette'}}" /&gt;</data>
  <data id="0C">&lt;s:data id="_0" f:Name="E1" f:Description="Entity Number 1" f:Labels="{Collection {Text 'Entity1'}}" /&gt;</data>
  <data id="0D">&lt;s:data id="_0" f:Name="E2" f:Description="Entity Number 2" f:Labels="{Collection {Text 'Entity2'}}" /&gt;</data>
  <data id="0E">&lt;s:data id="_0" f:Name="X" f:Labels="{Collection {Text 'Field X'}}" /&gt;</data>
  <data id="0F">&lt;s:data id="_0" f:Name="Y" f:Labels="{Collection {Text 'Field Y'}}" /&gt;</data>
  <data id="0G">&lt;s:data id="_0" f:Name="Z" f:Labels="{Collection {Text 'Field Z'}}" /&gt;</data>
  <data id="0H">&lt;s:data id="_0" f:Name="I" f:Description="Interface" f:Labels="{Collection {Text 'Interface'}}" /&gt;</data>
  <data id="0I">&lt;s:data id="_0" f:Name="If1" f:Labels="{Collection {Text 'Field 1'}}" /&gt;</data>
  <data id="0J">&lt;s:data id="_0" f:Name="If2" f:Labels="{Collection {Text 'Field 1'}}" /&gt;</data>
</bundle>
