//	Automatically generated by ResGenerator, on 19.01.2011
//	Do not edit manually.

namespace Epsitec.Common.Types
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources

		public static class Types
		{
			//	designer:cap/100G
			public static readonly global::Epsitec.Common.Types.EnumType BindingMode = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 16));
			//	designer:cap/1011
			public static readonly global::Epsitec.Common.Types.EnumType CultureMapSource = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 1));
			//	designer:cap/100T
			public static readonly global::Epsitec.Common.Types.EnumType FieldMembership = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 29));
			//	designer:cap/101
			public static readonly global::Epsitec.Common.Types.EnumType FieldOptions = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 0));
			//	designer:cap/100M
			public static readonly global::Epsitec.Common.Types.EnumType FieldRelation = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 22));
			//	designer:cap/10032
			public static readonly global::Epsitec.Common.Types.EnumType FieldSource = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 67));
			//	designer:cap/10A6
			public static readonly global::Epsitec.Common.Types.EnumType StringComparisonBehavior = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 6));
			//	designer:cap/10A
			public static readonly global::Epsitec.Common.Types.EnumType StringSearchBehavior = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 0));
			//	designer:cap/10011
			public static readonly global::Epsitec.Common.Types.EnumType StructuredTypeClass = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 33));
			//	designer:cap/100B1
			public static readonly global::Epsitec.Common.Types.EnumType TimeResolution = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 43));
			//	designer:cap/100V1
			public static readonly global::Epsitec.Common.Types.EnumType TypeCode = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 63));
			public static class Default
			{
				//	designer:cap/1003
				public static readonly global::Epsitec.Common.Types.BooleanType Boolean = (global::Epsitec.Common.Types.BooleanType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 3));
				//	designer:cap/10AI
				public static readonly global::Epsitec.Common.Types.BinaryType ByteArray = (global::Epsitec.Common.Types.BinaryType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 18));
				//	designer:cap/100H
				public static readonly global::Epsitec.Common.Types.DateType Date = (global::Epsitec.Common.Types.DateType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 17));
				//	designer:cap/100E1
				public static readonly global::Epsitec.Common.Types.OtherType DateSpan = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 46));
				//	designer:cap/100J
				public static readonly global::Epsitec.Common.Types.DateTimeType DateTime = (global::Epsitec.Common.Types.DateTimeType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 19));
				//	designer:cap/1004
				public static readonly global::Epsitec.Common.Types.DecimalType Decimal = (global::Epsitec.Common.Types.DecimalType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 4));
				//	designer:cap/100C1
				public static readonly global::Epsitec.Common.Types.OtherType DecimalRange = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 44));
				//	designer:cap/1005
				public static readonly global::Epsitec.Common.Types.DoubleType Double = (global::Epsitec.Common.Types.DoubleType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 5));
				//	designer:cap/100K
				public static readonly global::Epsitec.Common.Types.OtherType Druid = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 20));
				//	designer:cap/1006
				public static readonly global::Epsitec.Common.Types.IntegerType Integer = (global::Epsitec.Common.Types.IntegerType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 6));
				//	designer:cap/1007
				public static readonly global::Epsitec.Common.Types.LongIntegerType LongInteger = (global::Epsitec.Common.Types.LongIntegerType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 7));
				//	designer:cap/1015
				public static readonly global::Epsitec.Common.Types.OtherType Object = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 5));
				//	designer:cap/1008
				public static readonly global::Epsitec.Common.Types.StringType String = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 8));
				//	designer:cap/1016
				public static readonly global::Epsitec.Common.Types.StringType StringMultiline = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 6));
				//	designer:cap/10AJ
				public static readonly global::Epsitec.Common.Types.StringType StringNative = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 19));
				//	designer:cap/10002
				public static readonly global::Epsitec.Common.Types.OtherType SystemType = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 64));
				//	designer:cap/10AG
				public static readonly global::Epsitec.Common.Types.StringType Text = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 16));
				//	designer:cap/10AH
				public static readonly global::Epsitec.Common.Types.StringType TextMultiline = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 17));
				//	designer:cap/100I
				public static readonly global::Epsitec.Common.Types.TimeType Time = (global::Epsitec.Common.Types.TimeType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 18));
				//	designer:cap/100D1
				public static readonly global::Epsitec.Common.Types.OtherType TimeSpan = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 45));
				//	designer:cap/1009
				public static readonly global::Epsitec.Common.Types.OtherType Void = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 9));
			}
		}

		public static class Values
		{
			public static class BindingMode
			{
				//	designer:cap/100B
				public static global::Epsitec.Common.Types.Caption None
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 11));
					}
				}
				//	designer:cap/100C
				public static global::Epsitec.Common.Types.Caption OneTime
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 12));
					}
				}
				//	designer:cap/100D
				public static global::Epsitec.Common.Types.Caption OneWay
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 13));
					}
				}
				//	designer:cap/100E
				public static global::Epsitec.Common.Types.Caption OneWayToSource
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 14));
					}
				}
				//	designer:cap/100F
				public static global::Epsitec.Common.Types.Caption TwoWay
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 15));
					}
				}
			}

			public static class CultureMapSource
			{
				//	designer:cap/1014
				public static global::Epsitec.Common.Types.Caption DynamicMerge
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 4));
					}
				}
				//	designer:cap/1013
				public static global::Epsitec.Common.Types.Caption PatchModule
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 3));
					}
				}
				//	designer:cap/1012
				public static global::Epsitec.Common.Types.Caption ReferenceModule
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 2));
					}
				}
			}

			public static class FieldMembership
			{
				//	designer:cap/100S
				public static global::Epsitec.Common.Types.Caption Inherited
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 28));
					}
				}
				//	designer:cap/100R
				public static global::Epsitec.Common.Types.Caption Local
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 27));
					}
				}
				//	designer:cap/10AD
				public static global::Epsitec.Common.Types.Caption LocalOverride
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 13));
					}
				}
			}

			public static class FieldOptions
			{
				//	designer:cap/100P
				public static global::Epsitec.Common.Types.Caption None
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 25));
					}
				}
				//	designer:cap/10AE
				public static global::Epsitec.Common.Types.Caption Nullable
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 14));
					}
				}
				//	designer:cap/10AF
				public static global::Epsitec.Common.Types.Caption PrivateRelation
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 15));
					}
				}
			}

			public static class FieldRelation
			{
				//	designer:cap/100Q
				public static global::Epsitec.Common.Types.Caption Collection
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 26));
					}
				}
				//	designer:cap/100N
				public static global::Epsitec.Common.Types.Caption None
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 23));
					}
				}
				//	designer:cap/100O
				public static global::Epsitec.Common.Types.Caption Reference
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 24));
					}
				}
			}

			public static class FieldSource
			{
				//	designer:cap/10022
				public static global::Epsitec.Common.Types.Caption Expression
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 66));
					}
				}
				//	designer:cap/10012
				public static global::Epsitec.Common.Types.Caption Value
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 65));
					}
				}
			}

			public static class StringComparisonBehavior
			{
				//	designer:cap/10A7
				public static global::Epsitec.Common.Types.Caption CurrentCulture
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 7));
					}
				}
				//	designer:cap/10A8
				public static global::Epsitec.Common.Types.Caption CurrentCultureIgnoreCase
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 8));
					}
				}
				//	designer:cap/10A9
				public static global::Epsitec.Common.Types.Caption InvariantCulture
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 9));
					}
				}
				//	designer:cap/10AA
				public static global::Epsitec.Common.Types.Caption InvariantCultureIgnoreCase
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 10));
					}
				}
				//	designer:cap/10AB
				public static global::Epsitec.Common.Types.Caption Ordinal
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 11));
					}
				}
				//	designer:cap/10AC
				public static global::Epsitec.Common.Types.Caption OrdinalIgnoreCase
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 12));
					}
				}
			}

			public static class StringSearchBehavior
			{
				//	designer:cap/10A1
				public static global::Epsitec.Common.Types.Caption ExactMatch
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 1));
					}
				}
				//	designer:cap/10A5
				public static global::Epsitec.Common.Types.Caption MatchAnywhere
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 5));
					}
				}
				//	designer:cap/10A4
				public static global::Epsitec.Common.Types.Caption MatchEnd
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 4));
					}
				}
				//	designer:cap/10A3
				public static global::Epsitec.Common.Types.Caption MatchStart
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 3));
					}
				}
				//	designer:cap/10A2
				public static global::Epsitec.Common.Types.Caption WildcardMatch
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 10, 2));
					}
				}
			}

			public static class StructuredTypeClass
			{
				//	designer:cap/100V
				public static global::Epsitec.Common.Types.Caption Entity
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 31));
					}
				}
				//	designer:cap/10001
				public static global::Epsitec.Common.Types.Caption Interface
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 32));
					}
				}
				//	designer:cap/100U
				public static global::Epsitec.Common.Types.Caption None
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 30));
					}
				}
			}

			public static class TimeResolution
			{
				//	designer:cap/10071
				public static global::Epsitec.Common.Types.Caption Days
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 39));
					}
				}
				//	designer:cap/10021
				public static global::Epsitec.Common.Types.Caption Default
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 34));
					}
				}
				//	designer:cap/10061
				public static global::Epsitec.Common.Types.Caption Hours
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 38));
					}
				}
				//	designer:cap/10031
				public static global::Epsitec.Common.Types.Caption Milliseconds
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 35));
					}
				}
				//	designer:cap/10051
				public static global::Epsitec.Common.Types.Caption Minutes
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 37));
					}
				}
				//	designer:cap/10091
				public static global::Epsitec.Common.Types.Caption Months
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 41));
					}
				}
				//	designer:cap/10041
				public static global::Epsitec.Common.Types.Caption Seconds
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 36));
					}
				}
				//	designer:cap/10081
				public static global::Epsitec.Common.Types.Caption Weeks
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 40));
					}
				}
				//	designer:cap/100A1
				public static global::Epsitec.Common.Types.Caption Years
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 42));
					}
				}
			}

			public static class TypeCode
			{
				//	designer:cap/100O1
				public static global::Epsitec.Common.Types.Caption Binary
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 56));
					}
				}
				//	designer:cap/100G1
				public static global::Epsitec.Common.Types.Caption Boolean
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 48));
					}
				}
				//	designer:cap/100T1
				public static global::Epsitec.Common.Types.Caption Collection
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 61));
					}
				}
				//	designer:cap/100M1
				public static global::Epsitec.Common.Types.Caption Date
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 54));
					}
				}
				//	designer:cap/100L1
				public static global::Epsitec.Common.Types.Caption DateTime
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 53));
					}
				}
				//	designer:cap/100J1
				public static global::Epsitec.Common.Types.Caption Decimal
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 51));
					}
				}
				//	designer:cap/100K1
				public static global::Epsitec.Common.Types.Caption Double
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 52));
					}
				}
				//	designer:cap/100S1
				public static global::Epsitec.Common.Types.Caption Dynamic
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 60));
					}
				}
				//	designer:cap/100Q1
				public static global::Epsitec.Common.Types.Caption Enum
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 58));
					}
				}
				//	designer:cap/100H1
				public static global::Epsitec.Common.Types.Caption Integer
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 49));
					}
				}
				//	designer:cap/100F1
				public static global::Epsitec.Common.Types.Caption Invalid
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 47));
					}
				}
				//	designer:cap/100I1
				public static global::Epsitec.Common.Types.Caption LongInteger
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 50));
					}
				}
				//	designer:cap/100U1
				public static global::Epsitec.Common.Types.Caption Other
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 62));
					}
				}
				//	designer:cap/100P1
				public static global::Epsitec.Common.Types.Caption String
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 57));
					}
				}
				//	designer:cap/100R1
				public static global::Epsitec.Common.Types.Caption Structured
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 59));
					}
				}
				//	designer:cap/100N1
				public static global::Epsitec.Common.Types.Caption Time
				{
					get
					{
						return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 55));
					}
				}
			}
		}

		//	Code mapping for 'String' resources

		public static class Strings
		{
			//	designer:str/1
			public static string Empty
			{
				get
				{
					return global::Epsitec.Common.Types.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (0));
				}
			}

			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}

			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(global::Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static global::Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}

		static Res()
		{
			Res.Initialize (typeof (Res), "Common.Types");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new global::Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}

		public static global::Epsitec.Common.Support.ResourceManager Manager
		{
			get
			{
				return Res._manager;
			}
		}

		public static int ModuleId
		{
			get
			{
				return _moduleId;
			}
		}

		private static global::Epsitec.Common.Support.ResourceManager _manager = global::Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 1;
	}
}
