<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="Error.CannotConnectToLocalDatabase" id="A">{0} ne parvient pas à contacter la base de données.</data>
  <data name="Error.IncompatibleDatabase" id="A1">{0} a déterminé que la base de données n&amp;apos;est pas compatible.</data>
  <data name="Hint.Error.CannotConnectToLocalDatabase" id="A2">Vérifiez que le serveur Firebird est bien en exécution et que&lt;br/&gt;le pare-feu de Windows ne bloque pas ses accès.</data>
  <data name="Hint.Error.IncompatibleDatabase" id="A3">La base de données doit être migrée. Cette opération peut prendre queqlues&lt;br/&gt;minutes jusqu&amp;apos;à ce que {0} soit à nouveau opérationnel.</data>
</bundle>