<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="de">
  <data id="KK3">&lt;s:type id="_1" s:name="Epsitec.Common.Widgets.Command" /&gt;&lt;s:type id="_2" s:name="Epsitec.Common.Widgets.Shortcut" /&gt;&lt;s:data id="_0" f:_1.Statefull="False" f:_1.DefaultParameter="{Null}" f:Labels="{Collection {Text 'Gehen Sie auf die Ursache der Warnung'}}" /&gt;</data>
</bundle>