<bundle>
<field name='image.data'><ref target='bitmap' type='binary'/></field>
<field name='image.size'>960;48</field>
<field name='i.new'>0;24;24;24;0;6</field>
<field name='i.open'>24;24;24;24;0;6</field>
<field name='i.save'>48;24;24;24;0;6</field>
<field name='i.cut'>96;24;24;24;0;6</field>
<field name='i.copy'>120;24;24;24;0;6</field>
<field name='i.paste'>144;24;24;24;0;6</field>
<field name='i.back'>408;24;24;24;0;6</field>
<field name='i.forward'>432;24;24;24;0;6</field>
</bundle>
