<?xml version="1.0" encoding="utf-8"?>
<bundle name="_6313" caption="MasqueDeltaC" type="Form" culture="fr" rank="4">
  <data name="Source">
    <xml>
      <Form>
        <EI>[63081]</EI>
        <DBI>[6312]</DBI>
        <FD>
          <Guid>1db0813a-d982-4a57-b35c-45b1bbc6f691</Guid>
          <Type>Field</Type>
          <FI>[630A3]</FI>
          <SB>Normal</SB>
          <CR>10</CR>
          <RR>1</RR>
          <BPT>Normal</BPT>
          <BFS>None</BFS>
          <BFW>1</BFW>
          <DMo>True</DMo>
          <DAG>1cadef1f-3907-431f-be2f-56f0dbf081fd</DAG>
        </FD>
      </Form>
    </xml>
  </data>
  <data name="DefaultSize">
  </data>
  <data name="RootEntityId">
  </data>
</bundle>