<?xml version="1.0" encoding="utf-8"?>
<bundle name="_6312" caption="MasqueDeltaB" type="Form" culture="fr" rank="3">
  <data name="Source">
    <xml>
      <Form>
        <EI>[63081]</EI>
        <DBI>[6311]</DBI>
        <FD>
          <Guid>e145652c-7990-416e-976c-d6a800be6c8a</Guid>
          <Type>Field</Type>
          <FI>[630D3]</FI>
          <SB>Normal</SB>
          <CR>10</CR>
          <RR>1</RR>
          <BPT>Normal</BPT>
          <BFS>None</BFS>
          <BFW>1</BFW>
          <DHi>True</DHi>
        </FD>
        <FD>
          <Guid>719984bf-586c-42fc-b917-bd06f6f1b953</Guid>
          <Type>Field</Type>
          <FI>[63083]</FI>
          <SB>Normal</SB>
          <CR>10</CR>
          <RR>2</RR>
          <BPT>Normal</BPT>
          <BFS>None</BFS>
          <BFW>1</BFW>
          <DMd>True</DMd>
        </FD>
      </Form>
    </xml>
  </data>
  <data name="DefaultSize">
  </data>
  <data name="RootEntityId">
  </data>
</bundle>