//	Copyright © 2007-2008, EPSITEC SA, 1400 Yverdon-les-Bains, Switzerland
//	Author: Pierre ARNAUD, Maintainer: Pierre ARNAUD

using System.Collections.Generic;
using System.Threading;

namespace Epsitec.Common.IO
{
	/// <summary>
	/// The <c>WaitCondition</c> class can be used to wait for a condition to
	/// become true in a producer/consumer scenario. It makes sure that the
	/// reader never misses any event generated by the producer.
	/// </summary>
	public class WaitCondition
	{
		public WaitCondition()
		{
		}

		/// <summary>
		/// Waits for the specified condition to become true or for the timeout
		/// to be hit.
		/// </summary>
		/// <param name="condition">The condition.</param>
		/// <param name="timeout">The timeout.</param>
		/// <returns><c>true</c> if the condition was met.</returns>
		public bool Wait(ConditionPredicate condition, int timeout)
		{
			if (condition ())
			{
				return true;
			}

			int endTicks = System.Environment.TickCount + timeout;
			AutoResetEvent wait = new AutoResetEvent (false);

			try
			{
				lock (this.waits)
				{
					this.waits.Add (wait);
				}

				if (condition ())
				{
					return true;
				}
				
				while (true)
				{
					if (timeout == -1)
					{
						wait.WaitOne ();
					}
					else
					{
						int nowTicks = System.Environment.TickCount;
						int milliseconds = endTicks - nowTicks;

						if (milliseconds <= 0)
						{
							return condition ();
						}
						
						wait.WaitOne (milliseconds, false);
					}
					
					if (condition ())
					{
						return true;
					}
				}
			}
			finally
			{
				lock (this.waits)
				{
					this.waits.Remove (wait);
				}
			}
		}

		/// <summary>
		/// Signals an event. This will awake all consumers which are waiting
		/// for the condition to become true.
		/// </summary>
		public void Signal()
		{
			lock (this.waits)
			{
				foreach (AutoResetEvent wait in this.waits)
				{
					wait.Set ();
				}
			}
		}

		public delegate bool ConditionPredicate();

		private List<AutoResetEvent> waits = new List<AutoResetEvent> ();
	}
}
