//	Automatically generated by ResGenerator, on 27.02.2007
//	Do not edit manually.

namespace Epsitec.Common.Dialogs
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		public static class Commands
		{
			public static class Dialog
			{
				internal static void _Initialize() { }
				
				public static class File
				{
					internal static void _Initialize() { }
					
					public static readonly Epsitec.Common.Widgets.Command Delete = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 5));
					public static readonly Epsitec.Common.Widgets.Command NavigateNext = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 7));
					public static readonly Epsitec.Common.Widgets.Command NavigatePrev = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 6));
					public static readonly Epsitec.Common.Widgets.Command NewFolder = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 3));
					public static readonly Epsitec.Common.Widgets.Command ParentFolder = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 1));
					public static readonly Epsitec.Common.Widgets.Command Rename = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 4));
					public static class Favorites
					{
						internal static void _Initialize() { }
						
						public static readonly Epsitec.Common.Widgets.Command Add = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 8));
						public static readonly Epsitec.Common.Widgets.Command Down = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 11));
						public static readonly Epsitec.Common.Widgets.Command Remove = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 9));
						public static readonly Epsitec.Common.Widgets.Command ToggleSize = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 12));
						public static readonly Epsitec.Common.Widgets.Command Up = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (_moduleId, 10));
					}
				}
			}
			
			internal static void _Initialize()
			{
				Dialog.File._Initialize ();
				Dialog.File.Favorites._Initialize ();
			}
		}
		
		public static class CommandIds
		{
			public static class Dialog
			{
				
				public static class File
				{
					
					public const long Delete = 0x600000000005L;
					public const long NavigateNext = 0x600000000007L;
					public const long NavigatePrev = 0x600000000006L;
					public const long NewFolder = 0x600000000003L;
					public const long ParentFolder = 0x600000000001L;
					public const long Rename = 0x600000000004L;
					public static class Favorites
					{
						
						public const long Add = 0x600000000008L;
						public const long Down = 0x60000000000BL;
						public const long Remove = 0x600000000009L;
						public const long ToggleSize = 0x60000000000CL;
						public const long Up = 0x60000000000AL;
					}
				}
			}
		}
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static class Dialog
			{
				public static string Title { get { return Epsitec.Common.Dialogs.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (0)); } }
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _stringsBundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		//	Code mapping for 'Panel' resources
		
		public static void Initialize(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.DefineDefaultModuleName (name);
			Commands._Initialize ();
		}
		
		public static Epsitec.Common.Support.ResourceManager Manager
		{
			get { return _manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 6;
	}
}
