//	Copyright © 2010, EPSITEC SA, CH-1400 Yverdon-les-Bains, Switzerland
//	Author: Pierre ARNAUD, Maintainer: Pierre ARNAUD

using Epsitec.Common.Support.EntityEngine;
using Epsitec.Common.Support.Extensions;
using Epsitec.Common.Types;
using Epsitec.Common.Types.Collections;

using Epsitec.Cresus.Core.Business.Finance;
using Epsitec.Cresus.Core.Entities;

using Epsitec.Cresus.DataLayer.Context;

using System.Collections.Generic;
using System.Linq;

namespace Epsitec.Cresus.Core.Business.Finance.PriceCalculators
{
	public sealed class DocumentPriceCalculator : IDocumentPriceCalculator, System.IDisposable
	{
		public DocumentPriceCalculator(BusinessContext context, BusinessDocumentEntity document)
		{
			this.context     = context;
			this.document    = document;
			this.calculators = new List<AbstractPriceCalculator> ();
			this.groups      = new Stack<GroupPriceCalculator> ();
			this.suspender   = this.document.DisableEvents ();
		}


		public void UpdatePrices()
		{
			this.SortLines ();
			
			this.ComputeLinePrices ();
			this.ComputeTaxesAndGrandTotal (this.GetLastGroup ());
		}

		private void SortLines()
		{
			List<AbstractDocumentItemEntity> lines = new List<AbstractDocumentItemEntity> ();

			lines.AddRange (this.document.Lines.Where (x => x.GroupLevel > 0));
			lines.AddRange (this.document.Lines.Where (x => x.GroupLevel == 0 && !x.AutoGenerated));
			lines.AddRange (this.document.Lines.Where (x => x.GroupLevel == 0 && x.AutoGenerated));

			if (!Comparer.EqualObjects (lines, this.document.Lines))
			{
				this.document.Lines.Clear ();
				this.document.Lines.AddRange (lines);
			}
		}

		private void ComputeLinePrices()
		{
			this.currentState = State.None;

			this.calculators.Clear ();
			this.groups.Clear ();

			foreach (var line in this.document.Lines)
			{
				line.Process (this);
			}

			this.RecordCurrentGroup ();
		}

		private void ComputeTaxesAndGrandTotal(GroupPriceCalculator group)
		{
			if (group == null)
			{
				return;
			}

			DataContext context = this.context.DataContext;
			
			var taxReservoir   = new Reservoir<TaxDocumentItemEntity> (context, this.document.Lines.OfType<TaxDocumentItemEntity> ());
			var totalReservoir = new Reservoir<EndTotalDocumentItemEntity> (context, this.document.Lines.OfType<EndTotalDocumentItemEntity> ());

			Tax taxTotals = Tax.Combine (group.TaxDiscountable, group.TaxNotDiscountable);

			if (taxTotals == null)
			{
				return;
			}

			var taxInfos = from tax in taxTotals.RateAmounts
						   orderby tax.CodeRate ascending
						   select tax;

			var currency = this.document.BillingCurrencyCode;

			this.GenerateVatLines (taxReservoir, taxInfos, currency);
			this.GenerateGrandTotalLine (totalReservoir, taxTotals, currency);

			group.AdjustFinalPrices (taxTotals.TotalAmount);
		}

		private void GenerateVatLines(Reservoir<TaxDocumentItemEntity> reservoir, IOrderedEnumerable<TaxRateAmount> taxInfos, CurrencyCode currency)
		{
			reservoir.Pool.ForEach (line => this.document.Lines.Remove (line));
			
			foreach (var taxInfo in taxInfos)
			{
				var taxLine = reservoir.Pull ();

				taxLine.VatCode      = taxInfo.Code;
				taxLine.BaseAmount   = PriceCalculator.ClipPriceValue (taxInfo.Amount, currency);
				taxLine.Rate         = PriceCalculator.ClipTaxRateValue (taxInfo.Rate);
				taxLine.ResultingTax = PriceCalculator.ClipPriceValue (taxInfo.Tax, currency);

				this.document.Lines.Add (taxLine);
			}
		}

		private void GenerateGrandTotalLine(Reservoir<EndTotalDocumentItemEntity> reservoir, Tax taxTotals, CurrencyCode currency)
		{
			reservoir.Pool.ForEach (line => this.document.Lines.Remove (line));
			
			var grandTotalLine = reservoir.Pull ();

			grandTotalLine.PriceBeforeTax = PriceCalculator.ClipPriceValue (taxTotals.TotalAmount, currency);
			grandTotalLine.PriceAfterTax  = PriceCalculator.ClipPriceValue (taxTotals.TotalAmount + taxTotals.TotalTax, currency);

			this.document.Lines.Add (grandTotalLine);
		}

		#region Reservoir Class

		class Reservoir<T>
			where T : AbstractEntity, new ()
		{
			public Reservoir(DataContext context, IEnumerable<T> source)
			{
				this.context = context;
				this.pool = new Queue<T> (source);
			}

			public IEnumerable<T> Pool
			{
				get
				{
					return this.pool;
				}
			}

			public T Pull()
			{
				if (this.pool.Count > 0)
				{
					return this.pool.Dequeue ();
				}
				else
				{
					return this.context.CreateEntity<T> ();
				}
			}


			private readonly Queue<T> pool;
			private readonly DataContext context;
		}

		#endregion

		#region State Enum
		
		enum State
		{
			None,
			Article,
			SubTotal,
		}

#endregion

		#region IDocumentPriceCalculator Members

		public BusinessDocumentEntity Document
		{
			get
			{
				return this.document;
			}
		}

		void IDocumentPriceCalculator.Process(ArticlePriceCalculator calculator)
		{
			int groupLevel = calculator.ArticleItem.GroupLevel;

			if (this.currentState != State.Article)
			{
				//	We reached the first article line of a new group. Record the current
				//	group and create a new one for the current level.

				this.RecordCurrentGroup ();
				this.currentState = State.Article;
				this.currentGroup = new GroupPriceCalculator (groupLevel);
			}

			System.Diagnostics.Debug.Assert (this.currentGroup != null);
			System.Diagnostics.Debug.Assert (this.currentGroup.GroupLevel == groupLevel);

			if (this.currentGroup.GroupLevel != groupLevel)
			{
				//	TODO: implement multi-level articles ? or add a foolproof system in the UI to avoid that the user creates such invalid constructs...
				throw new System.NotImplementedException ("Found articles of different group levels without summarizing sub-totals");
			}

			this.calculators.Add (calculator);
			
			calculator.ComputePrice ();
			
			this.currentGroup.Add (calculator);
			this.IncludeSubgroups (this.currentGroup, groupLevel);
		}

		void IDocumentPriceCalculator.Process(SubTotalPriceCalculator calculator)
		{
			this.calculators.Add (calculator);

			int groupLevel = calculator.Item.GroupLevel;
			var localGroup = this.currentGroup;

			if (localGroup == null)
			{
				localGroup = new GroupPriceCalculator (groupLevel);
			}
			else if (localGroup.GroupLevel > groupLevel)
			{
				//	Summing groups of higher level into a new lower-level group. Add the
				//	groups of the higher level into the new local group, as if they were
				//	simple article lines.

				this.groups.Push (localGroup);

				localGroup = new GroupPriceCalculator (groupLevel);

				this.IncludeSubgroups (localGroup, groupLevel);
			}

			calculator.ComputePrice (localGroup);

			this.currentState = State.SubTotal;
			this.currentGroup = new GroupPriceCalculator (groupLevel);
			this.currentGroup.Add (calculator);
		}

		#endregion

		#region IDisposable Members

		public void Dispose()
		{
			this.suspender.Dispose ();
		}

		#endregion

		private void RecordCurrentGroup()
		{
			if (this.currentGroup != null)
			{
				this.groups.Push (this.currentGroup);
				this.currentGroup = null;
			}
		}


		private GroupPriceCalculator GetLastGroup()
		{
			if (this.groups.Count == 0)
			{
				return null;
			}
			else
			{
				return this.groups.Peek ();
			}
		}

		private void IncludeSubgroups(GroupPriceCalculator localGroup, int groupLevel)
		{
			while (this.groups.Count > 0 && this.groups.Peek ().GroupLevel > groupLevel)
			{
				localGroup.Add (this.groups.Pop ());
			}
		}
		
		private readonly BusinessContext				context;
		private readonly BusinessDocumentEntity			document;
		private readonly List<AbstractPriceCalculator>	calculators;
		private readonly Stack<GroupPriceCalculator>	groups;
		private readonly System.IDisposable				suspender;

		private GroupPriceCalculator			currentGroup;
		private State							currentState;
	}
}