//	Copyright © 2010, EPSITEC SA, CH-1400 Yverdon-les-Bains, Switzerland
//	Author: Daniel ROUX, Maintainer: Daniel ROUX

namespace Epsitec.Cresus.Compta.Accessors
{
	public enum ColumnType
	{
		None,

		Date,
		Débit,
		Crédit,
		SoldeDébit,
		SoldeCrédit,
		Pièce,
		Libellé,
		Titre,
		Montant,
		MontantTTC,
		MontantComplément,
		LibelléTVA,
		CodesTVA,
		CodeTVA,
		TauxTVA,
		CompteOrigineTVA,
		CompteTVA,
		Solde,
		Numéro,
		CP,
		Catégorie,
		Type,
		Groupe,
		CompteOuvBoucl,
		IndexOuvBoucl,
		Monnaie,
		TotalAutomatique,
		SoldeGraphique,

		Budget,
		BudgetProrata,
		BudgetFutur,
		BudgetFuturProrata,
		PériodePrécédente,
		PériodePénultième,
		BudgetPrécédent,
		
		Journal,
		Profondeur,
		Utilise,
		DateDébut,
		DateFin,
		Résumé,
		Permanent,
		Code,
		Raccourci,
		Utilisateur,
		NomComplet,
		MotDePasse,
		Admin,
		Présentations,
		Nom,
		Préfixe,
		Suffixe,
		Format,
		Incrément,
		IdentitéWindows,
		Désactivé,
		ParDéfaut,
		Exemple,
		Icône,
		Taux,
		Déduction,
		Chiffre,
		MontantFictif,
		Compte,
		IsMulti,
	}
}
