<?xml version="1.0" encoding="utf-8"?>
<bundle name="_KF02" caption="Essai" type="Panel" culture="fr" rank="4">
  <data name="Panel">
    <xml>
      <panel xmlns:s="http://www.epsitec.ch/XNS/storage-structure-1" xmlns:f="http://www.epsitec.ch/XNS/storage-fields-1">
        <s:storage s:root="_1" s:n_ext="2" s:n_typ="13" s:n_obj="21">
          <s:external s:name="_DataSource" />
          <s:external s:name="_ResourceManager" />
          <s:type id="_1" s:name="Epsitec.Common.UI.Panel" />
          <s:type id="_2" s:name="Epsitec.Common.Support.ResourceManager" />
          <s:type id="_3" s:name="Epsitec.Common.Types.DataObject" />
          <s:type id="_4" s:name="Epsitec.Common.Widgets.GroupBox" />
          <s:type id="_5" s:name="Epsitec.Common.Widgets.FrameBox" />
          <s:type id="_6" s:name="Epsitec.Common.Widgets.MetaButton" />
          <s:type id="_7" s:name="Epsitec.Common.Widgets.Layouts.LayoutEngine" />
          <s:type id="_8" s:name="Epsitec.Common.Widgets.Layouts.GridLayoutEngine" />
          <s:type id="_9" s:name="Epsitec.Common.Widgets.Layouts.RowDefinition" />
          <s:type id="_10" s:name="Epsitec.Common.Widgets.Layouts.ColumnDefinition" />
          <s:type id="_11" s:name="Epsitec.Common.UI.DataSourceMetadata" />
          <s:type id="_12" s:name="Epsitec.Common.UI.Panels.EditPanel" />
          <s:type id="_13" s:name="Epsitec.Common.UI.Panels.SearchPanel" />
          <s:object id="_1" s:type="_1" />
          <s:object id="_2" s:type="_4" />
          <s:object id="_3" s:type="_5" />
          <s:object id="_4" s:type="_6" />
          <s:object id="_5" s:type="_6" />
          <s:object id="_6" s:type="_5" />
          <s:object id="_7" s:type="_6" />
          <s:object id="_8" s:type="_5" />
          <s:object id="_9" s:type="_8" />
          <s:object id="_10" s:type="_9" />
          <s:object id="_11" s:type="_9" />
          <s:object id="_12" s:type="_10" />
          <s:object id="_13" s:type="_10" />
          <s:object id="_14" s:type="_6" />
          <s:object id="_15" s:type="_6" />
          <s:object id="_16" s:type="_4" />
          <s:object id="_17" s:type="_6" />
          <s:object id="_18" s:type="_6" />
          <s:object id="_19" s:type="_11" />
          <s:object id="_20" s:type="_12" />
          <s:object id="_21" s:type="_13" />
          <s:data id="_1" f:TabNavigationMode="ForwardTabPassive" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="VerticalFlow" f:PreferredWidth="200" f:PreferredHeight="412" f:Anchor="BottomLeft" f:Padding="20;20;20;20" f:_2.ResourceManager="{ExtRef _ResourceManager}" f:_1.BundleId="[KF02]" f:_3.DataContext="\[Binding Mode=TwoWay\]" f:Children="{Collection {ObjRef _2}, {ObjRef _7}, {ObjRef _8}}" f:DataSource="{ExtRef _DataSource}" f:DataSourceMetadata="{ObjRef _19}" f:EditionPanel="{ObjRef _20}" f:SearchPanel="{ObjRef _21}" f:Text="" />
          <s:data id="_2" f:TabNavigationMode="ForwardToChildren, ForwardOnly" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="HorizontalFlow" f:Margins="0;0;5;5" f:PreferredWidth="200" f:PreferredHeight="32" f:MinWidth="50" f:MinHeight="50" f:Dock="StackEnd" f:Anchor="None" f:CaptionId="[KF05]" f:Children="{Collection {ObjRef _3}, {ObjRef _6}}" />
          <s:data id="_3" f:TabNavigationMode="ForwardToChildren, ForwardOnly" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="HorizontalFlow" f:PreferredWidth="140" f:Margins="5;5;5;5" f:PreferredHeight="28" f:MinWidth="50" f:MinHeight="50" f:Padding="0;0;0;0" f:Dock="StackBegin" f:Anchor="None" f:Children="{Collection {ObjRef _4}, {ObjRef _5}}" f:Text="" />
          <s:data id="_4" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:PreferredWidth="55" f:Margins="5;5;5;5" f:Dock="StackBegin" f:Anchor="None" f:PreferredHeight="22" f:ActiveState="No" f:Text="" />
          <s:data id="_5" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:PreferredWidth="22" f:Margins="5;5;5;5" f:Dock="StackBegin" f:Anchor="None" f:PreferredHeight="22" f:ActiveState="No" f:Text="" />
          <s:data id="_6" f:TabNavigationMode="ForwardToChildren, ForwardOnly" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="HorizontalFlow" f:PreferredWidth="140" f:Margins="5;5;5;5" f:PreferredHeight="28" f:MinWidth="50" f:MinHeight="50" f:Padding="0;0;0;0" f:Dock="StackBegin" f:Anchor="None" f:Text="" />
          <s:data id="_7" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:Margins="5;5;5;5" f:Dock="StackEnd" f:Anchor="None" f:PreferredHeight="22" f:CommandObject="[0001]" f:ActiveState="No" />
          <s:data id="_8" f:TabNavigationMode="ForwardToChildren, ForwardOnly" f:ChildrenLayoutMode="Grid" f:ContainerLayoutMode="VerticalFlow" f:Margins="0;0;0;0" f:PreferredWidth="237" f:PreferredHeight="208" f:MinWidth="50" f:MinHeight="50" f:Padding="0;10;10;10" f:Dock="StackEnd" f:Anchor="None" f:HorizontalAlignment="Left" f:_7.LayoutEngine="{ObjRef _9}" f:Children="{Collection {ObjRef _14}, {ObjRef _15}, {ObjRef _16}}" f:Text="" />
          <s:data id="_9" f:ColumnDefinitions="{Collection {ObjRef _10}, {ObjRef _11}}" f:RowDefinitions="{Collection {ObjRef _12}, {ObjRef _13}}" />
          <s:data id="_10" f:Height="Auto" f:MinHeight="20" />
          <s:data id="_11" f:Height="Auto" f:MinHeight="20" />
          <s:data id="_12" f:Width="Auto" f:MinWidth="20" />
          <s:data id="_13" f:Width="Auto" f:MinWidth="20" />
          <s:data id="_14" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:Margins="5;5;5;5" f:Dock="None" f:Anchor="None" f:PreferredHeight="22" f:CommandObject="[0002]" f:ActiveState="No" f:_8.Column="0" f:_8.Row="0" />
          <s:data id="_15" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:Margins="5;5;5;5" f:Dock="None" f:Anchor="None" f:PreferredHeight="22" f:CommandObject="[0003]" f:ActiveState="No" f:PreferredWidth="69" f:_8.Column="1" f:_8.Row="0" />
          <s:data id="_16" f:TabNavigationMode="ForwardToChildren, ForwardOnly" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="HorizontalFlow" f:Margins="0;0;0;0" f:PreferredWidth="70" f:PreferredHeight="32" f:MinWidth="50" f:MinHeight="50" f:Dock="None" f:Anchor="None" f:CaptionId="[KF07]" f:_8.Column="0" f:_8.Row="1" f:Children="{Collection {ObjRef _17}, {ObjRef _18}}" />
          <s:data id="_17" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:Anchor="None" f:Dock="StackBegin" f:PreferredHeight="22" f:Margins="0;0;0;0" f:PreferredWidth="100" f:ActiveState="No" f:Text="" />
          <s:data id="_18" f:AutoFocus="True" f:AutoEngage="True" f:Aspect="IconButton" f:ContentAlignment="MiddleLeft" f:MinWidth="22" f:TabNavigationMode="None" f:MinHeight="22" f:Anchor="None" f:Dock="StackBegin" f:PreferredHeight="22" f:Margins="0;0;0;0" f:PreferredWidth="100" f:ActiveState="No" f:Text="" />
          <s:data id="_19" f:Fields="{Collection {Text '*;[KF0E]'}}" />
          <s:data id="_20" f:TabNavigationMode="ForwardTabPassive" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="VerticalFlow" f:PreferredWidth="276" f:PreferredHeight="346" f:Anchor="BottomLeft" f:Dock="None" f:Margins="0;0;0;0" f:Padding="20;20;20;20" f:_3.DataContext="\[Binding Mode=TwoWay\]" f:DataSource="{ExtRef _DataSource}" f:DataSourceMetadata="{ObjRef _19}" f:EditionPanel="{ObjRef _20}" f:Owner="{ObjRef _1}" f:SearchPanel="{ObjRef _21}" f:Text="" />
          <s:data id="_21" f:TabNavigationMode="ForwardTabPassive" f:ChildrenLayoutMode="Stacked" f:ContainerLayoutMode="VerticalFlow" f:PreferredWidth="200" f:PreferredHeight="412" f:Anchor="BottomLeft" f:Dock="None" f:Margins="0;0;0;0" f:Padding="20;20;20;20" f:_3.DataContext="\[Binding Mode=TwoWay\]" f:DataSource="{ExtRef _DataSource}" f:DataSourceMetadata="{ObjRef _19}" f:EditionPanel="{ObjRef _20}" f:Owner="{ObjRef _1}" f:SearchPanel="{ObjRef _21}" f:Text="" />
        </s:storage>
      </panel>
    </xml>
  </data>
  <data name="DefaultSize">200;412</data>
  <data name="RootEntityId"></data>
</bundle>