<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Typ.Default.StringMulti" id="2">&lt;s:type id="_1" s:name="*aT" /&gt;&lt;s:data id="_0" f:Name="Default.StringMulti" f:Icon="" f:_1.SystemType="C:System.String" f:_1.DefaultController="String" f:_1.DefaultControllerParameters="Mode=Multiline" f:Labels="{Collection {Text 'Type String de .NET'}}" /&gt;</data>
  <data id="08">&lt;s:type id="_1" s:name="*aT" /&gt;&lt;s:data id="_0" f:_1.SystemType="C:System.String" f:_1.DefaultController="String" f:_1.DefaultControllerParameters="Mode=Multiline" /&gt;</data>
</bundle>