//	Copyright © 2011, EPSITEC SA, CH-1400 Yverdon-les-Bains, Switzerland
//	Author: Pierre ARNAUD, Maintainer: Pierre ARNAUD

using Epsitec.Common.Types;

namespace Epsitec.Cresus.Core.Business
{
	/// <summary>
	/// The <c>DocumentItemAttributes</c> enumeration defines the attributes which can
	/// be applied to a document item.
	/// </summary>
	[DesignerVisible]
	[System.Flags]
	public enum DocumentItemAttributes
	{
		/// <summary>
		/// Default.
		/// </summary>
		None			= 0,

		/// <summary>
		/// The line is hidden, but still considered by the price calculator.
		/// </summary>
		Hidden			= 0x0001,

		/// <summary>
		/// The line is generated automatically.
		/// </summary>
		AutoGenerated	= 0x0002,

		/// <summary>
		/// The line is only for information; it won't be summed by the price calculator.
		/// </summary>
		ProFormaOnly	= 0x0004,
	}
}
