//	Automatically generated by ResGenerator, on 04.04.2005 16:25:46
//	Do not edit manually.

namespace Epsitec.App.DocumentEditor
{
	public sealed class Res
	{
		public sealed class Strings
		{
			public sealed class Menu
			{
				public static string Edition { get { return GetText ("Strings", "Menu", "Edition"); } }
				public static string File { get { return GetText ("Strings", "Menu", "File"); } }
				public static string Objects { get { return GetText ("Strings", "Menu", "Objects"); } }
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _bundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialise(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.SetupApplication (name);
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
	}
}
