//	Automatically generated by ResGenerator, on 04.10.2005 08:20:23
//	Do not edit manually.

namespace Epsitec.App.DocumentEditor
{
	public sealed class Res
	{
		public sealed class Strings
		{
			public sealed class Application
			{
				public static string TitleDoc { get { return GetText ("Strings", "Application", "TitleDoc"); } }
				public static string TitlePic { get { return GetText ("Strings", "Application", "TitlePic"); } }
				public static string TitleShort { get { return GetText ("Strings", "Application", "TitleShort"); } }
				public static string TitleTxt { get { return GetText ("Strings", "Application", "TitleTxt"); } }
				public static string Type { get { return GetText ("Strings", "Application", "Type"); } }
			}
			
			public sealed class Dialog
			{
				public static string FileCol { get { return GetText ("Strings", "Dialog", "FileCol"); } }
				public static string FileDoc { get { return GetText ("Strings", "Dialog", "FileDoc"); } }
				public static string FileMod { get { return GetText ("Strings", "Dialog", "FileMod"); } }
				public static string FilePic { get { return GetText ("Strings", "Dialog", "FilePic"); } }
				public sealed class About
				{
					public static string Copyright { get { return GetText ("Strings", "Dialog", "About", "Copyright"); } }
					public static string Demo { get { return GetText ("Strings", "Dialog", "About", "Demo"); } }
					public static string Expired { get { return GetText ("Strings", "Dialog", "About", "Expired"); } }
					public static string Freeware { get { return GetText ("Strings", "Dialog", "About", "Freeware"); } }
					public static string Key { get { return GetText ("Strings", "Dialog", "About", "Key"); } }
					public static string Language { get { return GetText ("Strings", "Dialog", "About", "Language"); } }
					public static string Link { get { return GetText ("Strings", "Dialog", "About", "Link"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "About", "Title"); } }
					public static string Version { get { return GetText ("Strings", "Dialog", "About", "Version"); } }
					public static string Web { get { return GetText ("Strings", "Dialog", "About", "Web"); } }
				}
				
				public sealed class Button
				{
					public static string Cancel { get { return GetText ("Strings", "Dialog", "Button", "Cancel"); } }
					public static string Close { get { return GetText ("Strings", "Dialog", "Button", "Close"); } }
					public static string Help { get { return GetText ("Strings", "Dialog", "Button", "Help"); } }
					public static string OK { get { return GetText ("Strings", "Dialog", "Button", "OK"); } }
				}
				
				public sealed class Download
				{
					public static string Actual { get { return GetText ("Strings", "Dialog", "Download", "Actual"); } }
					public static string Available { get { return GetText ("Strings", "Dialog", "Download", "Available"); } }
					public static string Link { get { return GetText ("Strings", "Dialog", "Download", "Link"); } }
					public static string Nothing { get { return GetText ("Strings", "Dialog", "Download", "Nothing"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Download", "Title"); } }
					public static string UpToDate { get { return GetText ("Strings", "Dialog", "Download", "UpToDate"); } }
				}
				
				public sealed class Export
				{
					public static string Title { get { return GetText ("Strings", "Dialog", "Export", "Title"); } }
					public static string Title1 { get { return GetText ("Strings", "Dialog", "Export", "Title1"); } }
					public static string Title2 { get { return GetText ("Strings", "Dialog", "Export", "Title2"); } }
					public sealed class Button
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "Export", "Button", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "Export", "Button", "OK"); } }
					}
					
					public sealed class Tooltip
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "Export", "Tooltip", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "Export", "Tooltip", "OK"); } }
					}
				}
				
				public sealed class ExportPDF
				{
					public static string Title1 { get { return GetText ("Strings", "Dialog", "ExportPDF", "Title1"); } }
					public static string Title2 { get { return GetText ("Strings", "Dialog", "ExportPDF", "Title2"); } }
					public sealed class Button
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "ExportPDF", "Button", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "ExportPDF", "Button", "OK"); } }
					}
					
					public sealed class TabPage
					{
						public static string Color { get { return GetText ("Strings", "Dialog", "ExportPDF", "TabPage", "Color"); } }
						public static string Generic { get { return GetText ("Strings", "Dialog", "ExportPDF", "TabPage", "Generic"); } }
						public static string Image { get { return GetText ("Strings", "Dialog", "ExportPDF", "TabPage", "Image"); } }
						public static string Publisher { get { return GetText ("Strings", "Dialog", "ExportPDF", "TabPage", "Publisher"); } }
					}
					
					public sealed class Tooltip
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "ExportPDF", "Tooltip", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "ExportPDF", "Tooltip", "OK"); } }
					}
				}
				
				public sealed class Glyphs
				{
					public static string Font { get { return GetText ("Strings", "Dialog", "Glyphs", "Font"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Glyphs", "Title"); } }
					public sealed class Button
					{
						public static string Insert { get { return GetText ("Strings", "Dialog", "Glyphs", "Button", "Insert"); } }
					}
					
					public sealed class Family
					{
						public static string Business { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "Business"); } }
						public static string GreekLower { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "GreekLower"); } }
						public static string GreekUpper { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "GreekUpper"); } }
						public static string List { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "List"); } }
						public static string Math { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "Math"); } }
						public static string Space { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "Space"); } }
						public static string Symbol { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "Symbol"); } }
						public static string Typo { get { return GetText ("Strings", "Dialog", "Glyphs", "Family", "Typo"); } }
					}
					
					public sealed class TabPage
					{
						public static string Array { get { return GetText ("Strings", "Dialog", "Glyphs", "TabPage", "Array"); } }
						public static string List { get { return GetText ("Strings", "Dialog", "Glyphs", "TabPage", "List"); } }
					}
					
					public sealed class Tooltip
					{
						public static string ArrayMinus { get { return GetText ("Strings", "Dialog", "Glyphs", "Tooltip", "ArrayMinus"); } }
						public static string ArrayPlus { get { return GetText ("Strings", "Dialog", "Glyphs", "Tooltip", "ArrayPlus"); } }
						public static string CurrentFont { get { return GetText ("Strings", "Dialog", "Glyphs", "Tooltip", "CurrentFont"); } }
						public static string Insert { get { return GetText ("Strings", "Dialog", "Glyphs", "Tooltip", "Insert"); } }
					}
				}
				
				public sealed class Infos
				{
					public static string Title { get { return GetText ("Strings", "Dialog", "Infos", "Title"); } }
				}
				
				public sealed class Key
				{
					public static string Expired { get { return GetText ("Strings", "Dialog", "Key", "Expired"); } }
					public static string Label { get { return GetText ("Strings", "Dialog", "Key", "Label"); } }
					public static string Number { get { return GetText ("Strings", "Dialog", "Key", "Number"); } }
					public static string RadioDemo { get { return GetText ("Strings", "Dialog", "Key", "RadioDemo"); } }
					public static string RadioFull { get { return GetText ("Strings", "Dialog", "Key", "RadioFull"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Key", "Title"); } }
				}
				
				public sealed class Open
				{
					public static string TitleCol { get { return GetText ("Strings", "Dialog", "Open", "TitleCol"); } }
					public static string TitleDoc { get { return GetText ("Strings", "Dialog", "Open", "TitleDoc"); } }
					public static string TitleMod { get { return GetText ("Strings", "Dialog", "Open", "TitleMod"); } }
					public static string TitlePic { get { return GetText ("Strings", "Dialog", "Open", "TitlePic"); } }
				}
				
				public sealed class PageStack
				{
					public static string Help1 { get { return GetText ("Strings", "Dialog", "PageStack", "Help1"); } }
					public static string Help2 { get { return GetText ("Strings", "Dialog", "PageStack", "Help2"); } }
					public static string Help3 { get { return GetText ("Strings", "Dialog", "PageStack", "Help3"); } }
					public static string Help4 { get { return GetText ("Strings", "Dialog", "PageStack", "Help4"); } }
					public static string Help5 { get { return GetText ("Strings", "Dialog", "PageStack", "Help5"); } }
					public static string Layer { get { return GetText ("Strings", "Dialog", "PageStack", "Layer"); } }
					public static string Page { get { return GetText ("Strings", "Dialog", "PageStack", "Page"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "PageStack", "Title"); } }
					public sealed class Button
					{
						public static string Current { get { return GetText ("Strings", "Dialog", "PageStack", "Button", "Current"); } }
					}
					
					public sealed class Tooltip
					{
						public static string Current { get { return GetText ("Strings", "Dialog", "PageStack", "Tooltip", "Current"); } }
					}
				}
				
				public sealed class Print
				{
					public static string Title { get { return GetText ("Strings", "Dialog", "Print", "Title"); } }
					public sealed class Button
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "Print", "Button", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "Print", "Button", "OK"); } }
					}
					
					public sealed class TabPage
					{
						public static string Param { get { return GetText ("Strings", "Dialog", "Print", "TabPage", "Param"); } }
						public static string Printer { get { return GetText ("Strings", "Dialog", "Print", "TabPage", "Printer"); } }
						public static string Publisher { get { return GetText ("Strings", "Dialog", "Print", "TabPage", "Publisher"); } }
					}
					
					public sealed class Tooltip
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "Print", "Tooltip", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "Print", "Tooltip", "OK"); } }
					}
				}
				
				public sealed class Save
				{
					public static string Question1 { get { return GetText ("Strings", "Dialog", "Save", "Question1"); } }
					public static string Question2 { get { return GetText ("Strings", "Dialog", "Save", "Question2"); } }
					public static string TitleCol { get { return GetText ("Strings", "Dialog", "Save", "TitleCol"); } }
					public static string TitleDoc { get { return GetText ("Strings", "Dialog", "Save", "TitleDoc"); } }
					public static string TitleMod { get { return GetText ("Strings", "Dialog", "Save", "TitleMod"); } }
					public static string TitlePic { get { return GetText ("Strings", "Dialog", "Save", "TitlePic"); } }
				}
				
				public sealed class Settings
				{
					public static string Adorner { get { return GetText ("Strings", "Dialog", "Settings", "Adorner"); } }
					public static string AutoChecker { get { return GetText ("Strings", "Dialog", "Settings", "AutoChecker"); } }
					public static string AutoUpdate { get { return GetText ("Strings", "Dialog", "Settings", "AutoUpdate"); } }
					public static string FineCursor { get { return GetText ("Strings", "Dialog", "Settings", "FineCursor"); } }
					public static string Mouse { get { return GetText ("Strings", "Dialog", "Settings", "Mouse"); } }
					public static string MouseWheel { get { return GetText ("Strings", "Dialog", "Settings", "MouseWheel"); } }
					public static string MouseZoom { get { return GetText ("Strings", "Dialog", "Settings", "MouseZoom"); } }
					public static string RadioDocument { get { return GetText ("Strings", "Dialog", "Settings", "RadioDocument"); } }
					public static string RadioGlobal { get { return GetText ("Strings", "Dialog", "Settings", "RadioGlobal"); } }
					public static string Screen { get { return GetText ("Strings", "Dialog", "Settings", "Screen"); } }
					public static string ScreenDpi { get { return GetText ("Strings", "Dialog", "Settings", "ScreenDpi"); } }
					public static string SplashScreen { get { return GetText ("Strings", "Dialog", "Settings", "SplashScreen"); } }
					public static string Startup { get { return GetText ("Strings", "Dialog", "Settings", "Startup"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Settings", "Title"); } }
					public sealed class TabPage
					{
						public static string Format { get { return GetText ("Strings", "Dialog", "Settings", "TabPage", "Format"); } }
						public static string Grid { get { return GetText ("Strings", "Dialog", "Settings", "TabPage", "Grid"); } }
						public static string Guides { get { return GetText ("Strings", "Dialog", "Settings", "TabPage", "Guides"); } }
						public static string Misc { get { return GetText ("Strings", "Dialog", "Settings", "TabPage", "Misc"); } }
						public static string Move { get { return GetText ("Strings", "Dialog", "Settings", "TabPage", "Move"); } }
					}
				}
				
				public sealed class Tooltip
				{
					public static string Close { get { return GetText ("Strings", "Dialog", "Tooltip", "Close"); } }
					public static string Help { get { return GetText ("Strings", "Dialog", "Tooltip", "Help"); } }
					public static string Resize { get { return GetText ("Strings", "Dialog", "Tooltip", "Resize"); } }
				}
				
				public sealed class Update
				{
					public static string Address1 { get { return GetText ("Strings", "Dialog", "Update", "Address1"); } }
					public static string Address2 { get { return GetText ("Strings", "Dialog", "Update", "Address2"); } }
					public static string BuyDemo { get { return GetText ("Strings", "Dialog", "Update", "BuyDemo"); } }
					public static string BuyFreeware { get { return GetText ("Strings", "Dialog", "Update", "BuyFreeware"); } }
					public static string BuyFull { get { return GetText ("Strings", "Dialog", "Update", "BuyFull"); } }
					public static string Fax1 { get { return GetText ("Strings", "Dialog", "Update", "Fax1"); } }
					public static string Fax2 { get { return GetText ("Strings", "Dialog", "Update", "Fax2"); } }
					public static string Limit { get { return GetText ("Strings", "Dialog", "Update", "Limit"); } }
					public static string Mail1 { get { return GetText ("Strings", "Dialog", "Update", "Mail1"); } }
					public static string Mail2 { get { return GetText ("Strings", "Dialog", "Update", "Mail2"); } }
					public static string Mail3 { get { return GetText ("Strings", "Dialog", "Update", "Mail3"); } }
					public static string Over { get { return GetText ("Strings", "Dialog", "Update", "Over"); } }
					public static string Phone1 { get { return GetText ("Strings", "Dialog", "Update", "Phone1"); } }
					public static string Phone2 { get { return GetText ("Strings", "Dialog", "Update", "Phone2"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Update", "Title"); } }
					public static string Version { get { return GetText ("Strings", "Dialog", "Update", "Version"); } }
					public static string Web1 { get { return GetText ("Strings", "Dialog", "Update", "Web1"); } }
					public static string Web2 { get { return GetText ("Strings", "Dialog", "Update", "Web2"); } }
					public static string Web3 { get { return GetText ("Strings", "Dialog", "Update", "Web3"); } }
				}
				
				public sealed class Warning
				{
					public static string Text1 { get { return GetText ("Strings", "Dialog", "Warning", "Text1"); } }
					public static string Text2 { get { return GetText ("Strings", "Dialog", "Warning", "Text2"); } }
					public static string Text3 { get { return GetText ("Strings", "Dialog", "Warning", "Text3"); } }
				}
			}
			
			public sealed class LastFiles
			{
				public static string None { get { return GetText ("Strings", "LastFiles", "None"); } }
			}
			
			public sealed class Menu
			{
				public sealed class Help
				{
					public static string About { get { return GetText ("Strings", "Menu", "Help", "About"); } }
					public static string Key { get { return GetText ("Strings", "Menu", "Help", "Key"); } }
					public static string Update { get { return GetText ("Strings", "Menu", "Help", "Update"); } }
				}
				
				public sealed class Main
				{
					public static string Array { get { return GetText ("Strings", "Menu", "Main", "Array"); } }
					public static string Debug { get { return GetText ("Strings", "Menu", "Main", "Debug"); } }
					public static string Document { get { return GetText ("Strings", "Menu", "Main", "Document"); } }
					public static string Edit { get { return GetText ("Strings", "Menu", "Main", "Edit"); } }
					public static string File { get { return GetText ("Strings", "Menu", "Main", "File"); } }
					public static string Help { get { return GetText ("Strings", "Menu", "Main", "Help"); } }
					public static string Objects { get { return GetText ("Strings", "Menu", "Main", "Objects"); } }
					public static string Show { get { return GetText ("Strings", "Menu", "Main", "Show"); } }
				}
			}
			
			public sealed class Ribbon
			{
				public static string Main { get { return GetText ("Strings", "Ribbon", "Main"); } }
				public static string Objects { get { return GetText ("Strings", "Ribbon", "Objects"); } }
				public static string Oper { get { return GetText ("Strings", "Ribbon", "Oper"); } }
				public static string Text { get { return GetText ("Strings", "Ribbon", "Text"); } }
			}
			
			public sealed class Status
			{
				public sealed class Document
				{
					public static string Format { get { return GetText ("Strings", "Status", "Document", "Format"); } }
				}
				
				public sealed class Modif
				{
					public static string Default { get { return GetText ("Strings", "Status", "Modif", "Default"); } }
				}
				
				public sealed class Objects
				{
					public static string Level { get { return GetText ("Strings", "Status", "Objects", "Level"); } }
					public static string Select { get { return GetText ("Strings", "Status", "Objects", "Select"); } }
				}
				
				public sealed class Zoom
				{
					public static string Value { get { return GetText ("Strings", "Status", "Zoom", "Value"); } }
				}
			}
			
			public sealed class TabPage
			{
				public static string Autos { get { return GetText ("Strings", "TabPage", "Autos"); } }
				public static string Layers { get { return GetText ("Strings", "TabPage", "Layers"); } }
				public static string Operations { get { return GetText ("Strings", "TabPage", "Operations"); } }
				public static string Pages { get { return GetText ("Strings", "TabPage", "Pages"); } }
				public static string Principal { get { return GetText ("Strings", "TabPage", "Principal"); } }
				public static string Styles { get { return GetText ("Strings", "TabPage", "Styles"); } }
			}
			
			public sealed class Tooltip
			{
				public sealed class Ruler
				{
					public static string Drag { get { return GetText ("Strings", "Tooltip", "Ruler", "Drag"); } }
				}
				
				public sealed class TabBook
				{
					public static string Close { get { return GetText ("Strings", "Tooltip", "TabBook", "Close"); } }
				}
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _bundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialise(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.SetupApplication (name);
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
	}
}
