<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Val.LabelLayout.Label_3475_70_X_36" id="G102">&lt;s:data id="_0" f:Name="Label_3475_70_X_36" f:Labels="{Collection {Text 'Etiquette 3475 70x36'}}" /&gt;</data>
  <data name="Typ.LabelLayout" id="G002">&lt;s:type id="_1" s:name="*aT" /&gt;&lt;s:type id="_2" s:name="*eT" /&gt;&lt;s:data id="_0" f:Name="LabelLayout" f:_1.SystemType="E:Epsitec.Cresus.WebCore.Server.Core.Extraction.LabelLayout, Cresus.Core.Server" f:_2.EnumValues="{Collection {Text '0 [A1G102]'}}" f:Labels="{Collection {Text 'Choix d&amp;amp;apos;étiquette'}}" /&gt;</data>
</bundle>