<bundle name="strings" type="String">
  <data name="title.SettingsWindow">Réglages</data>
  <data name="group.Options">Options de premier rang</data>
  <data name="label.Help">Aide</data>
  <data name="label.Cancel">Annuler</data>
  <data name="label.Apply">Applique</data>
  <data name="label.ScriptEditor">Editeur de scripts</data>
  <data name="data.ValueA">Nom d&amp;apos;utilisateur</data>
  <data name="data.ValueB">Âge</data>
</bundle>