<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Cmd.New" id="01">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Cap.New" id="02">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Typ.ResourceCaption" id="06">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="3" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="*aT" /&gt;&lt;s:type id="_3" s:name="*S" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_3" /&gt;&lt;s:data id="_1" f:_2.ComplexType="{ObjRef _2}" f:_2.DefaultController="{Null}" f:Name="Resource.Caption" /&gt;&lt;s:data id="_2" f:Class="Entity" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
  <data name="Typ.ResourceString" id="07">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="3" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="*aT" /&gt;&lt;s:type id="_3" s:name="*S" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_3" /&gt;&lt;s:data id="_1" f:_2.ComplexType="{ObjRef _2}" f:_2.DefaultController="{Null}" f:Name="Resource.String" /&gt;&lt;s:data id="_2" f:Class="Entity" f:Fields="{Collection {Text '[7008];[1008];0;[7008]'}, {Text '[700A];[1008];1;[700A]'}}" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
  <data name="Val.New" id="04">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Fld.ResourceString.Text" id="08" mod="1">&lt;s:data id="_0" f:Name="Text" f:Labels="{Collection {Text 'Texte'}}" /&gt;</data>
  <data name="Fld.ResourceString.About" id="0A" mod="1">&lt;s:data id="_0" f:Name="About" f:Labels="{Collection {Text 'Commentaire'}}" /&gt;</data>
</bundle>