//	Automatically generated by ResGenerator, on 27.05.2008
//	Do not edit manually.

namespace Epsitec.App.Dolphin
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static class Assembler
			{
				public static class Expression
				{
					public static class Error
					{
						//	designer:str/732A4
						public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554570)); } }
						//	designer:str/732B4
						public static string Unary { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554571)); } }
						public static class Binary
						{
							//	designer:str/732C4
							public static string DivZero { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554572)); } }
							//	designer:str/732D4
							public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554573)); } }
						}
					}
				}
				
				public static class Instruction
				{
					public static class Error
					{
						//	designer:str/73284
						public static string Overflow { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554568)); } }
						//	designer:str/73294
						public static string RelOverflow { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554569)); } }
					}
				}
				
				public static class Message
				{
					//	designer:str/732R3
					public static string Empty { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554555)); } }
					//	designer:str/732T3
					public static string Error { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554557)); } }
					//	designer:str/732S3
					public static string OK { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554556)); } }
				}
				
				public static class Number
				{
					public static class Error
					{
						//	designer:str/732H4
						public static string Binary { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554577)); } }
						//	designer:str/732F4
						public static string Decimal { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554575)); } }
						//	designer:str/732I4
						public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554578)); } }
						//	designer:str/732G4
						public static string Hexa { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554576)); } }
					}
				}
				
				public static class Pseudo
				{
					public static class Error
					{
						//	designer:str/73214
						public static string Default { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554561)); } }
						//	designer:str/73204
						public static string End { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554560)); } }
						//	designer:str/732V3
						public static string Loc { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554559)); } }
						//	designer:str/732U3
						public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554558)); } }
					}
				}
				
				public static class Value
				{
					public static class Error
					{
						//	designer:str/732E4
						public static string Undefined { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554574)); } }
					}
				}
				
				public static class Var
				{
					public static class Error
					{
						//	designer:str/73274
						public static string LabelRedefine { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554567)); } }
						//	designer:str/73234
						public static string Name { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554563)); } }
						//	designer:str/73254
						public static string NoRegister { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554565)); } }
						//	designer:str/73244
						public static string Redefine { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554564)); } }
						//	designer:str/73224
						public static string Register { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554562)); } }
						//	designer:str/73264
						public static string WrongLabel { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554566)); } }
					}
				}
			}
			
			public static class Bus
			{
				public static class Title
				{
					//	designer:str/732I
					public static string Address { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554450)); } }
					//	designer:str/732H
					public static string Data { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554449)); } }
					//	designer:str/732S
					public static string Register { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554460)); } }
				}
			}
			
			public static class Calm
			{
				public static class Ass
				{
					//	designer:str/73231
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554467)); } }
					//	designer:str/73241
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554468)); } }
				}
				
				public static class Big
				{
					//	designer:str/73211
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554465)); } }
				}
				
				public static class Err
				{
					//	designer:str/73261
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554470)); } }
					//	designer:str/73251
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554469)); } }
				}
				
				public static class Full
				{
					//	designer:str/73221
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554466)); } }
				}
				
				public static class Open
				{
					//	designer:str/732U
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554462)); } }
				}
				
				public static class Save
				{
					//	designer:str/732V
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554463)); } }
				}
				
				public static class Show
				{
					//	designer:str/73201
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554464)); } }
				}
				
				public static class Title
				{
					//	designer:str/732T
					public static string Main { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554461)); } }
				}
			}
			
			public static class Code
			{
				public static class Add
				{
					//	designer:str/732R
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554459)); } }
				}
				
				public static class PC
				{
					//	designer:str/732K
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554452)); } }
					//	designer:str/732L
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554453)); } }
				}
				
				public static class RAM
				{
					//	designer:str/732M
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554454)); } }
					//	designer:str/732N
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554455)); } }
				}
				
				public static class ROM
				{
					//	designer:str/732O
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554456)); } }
					//	designer:str/732P
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554457)); } }
				}
				
				public static class Sub
				{
					//	designer:str/732Q
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554458)); } }
				}
				
				public static class Title
				{
					//	designer:str/732J
					public static string Data { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554451)); } }
					//	designer:str/732N1
					public static string Register { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554487)); } }
				}
			}
			
			public static class Command
			{
				public static class About
				{
					//	designer:str/7325
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554437)); } }
				}
				
				public static class Bold
				{
					//	designer:str/732B3
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554539)); } }
				}
				
				public static class Clock0
				{
					//	designer:str/73202
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554496)); } }
					//	designer:str/73262
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554502)); } }
				}
				
				public static class Clock1
				{
					//	designer:str/732V1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554495)); } }
					//	designer:str/73212
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554497)); } }
				}
				
				public static class Clock2
				{
					//	designer:str/732U1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554494)); } }
					//	designer:str/73222
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554498)); } }
				}
				
				public static class Clock3
				{
					//	designer:str/732T1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554493)); } }
					//	designer:str/73232
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554499)); } }
				}
				
				public static class Clock4
				{
					//	designer:str/732S1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554492)); } }
					//	designer:str/73242
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554500)); } }
				}
				
				public static class Clock5
				{
					//	designer:str/732R1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554491)); } }
					//	designer:str/73252
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554501)); } }
				}
				
				public static class Clock6
				{
					//	designer:str/732Q1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554490)); } }
					//	designer:str/732P1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554489)); } }
				}
				
				public static class Display
				{
					public static class Active
					{
						//	designer:str/732L3
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554549)); } }
						//	designer:str/732O3
						public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554552)); } }
					}
					
					public static class Clear
					{
						//	designer:str/732M3
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554550)); } }
						//	designer:str/732Q3
						public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554554)); } }
					}
					
					public static class Techno
					{
						//	designer:str/732P3
						public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554553)); } }
						public static class CRT
						{
							//	designer:str/732L2
							public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554517)); } }
						}
						
						public static class LCD
						{
							//	designer:str/732M2
							public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554518)); } }
						}
					}
				}
				
				public static class Italic
				{
					//	designer:str/73293
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554537)); } }
				}
				
				public static class Keyboard
				{
					//	designer:str/732N3
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554551)); } }
					public static class Arrows
					{
						//	designer:str/732N2
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554519)); } }
					}
					
					public static class Numeric
					{
						//	designer:str/732O2
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554520)); } }
					}
				}
				
				public static class Look
				{
					//	designer:str/7326
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554438)); } }
				}
				
				public static class New
				{
					//	designer:str/7322
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554434)); } }
				}
				
				public static class Open
				{
					//	designer:str/7323
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554435)); } }
				}
				
				public static class Read
				{
					//	designer:str/732I2
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554514)); } }
					//	designer:str/732G2
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554512)); } }
				}
				
				public static class Run
				{
					//	designer:str/732J2
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554515)); } }
					//	designer:str/732O1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554488)); } }
				}
				
				public static class Save
				{
					//	designer:str/7324
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554436)); } }
				}
				
				public static class Step
				{
					//	designer:str/732B2
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554507)); } }
					//	designer:str/732A2
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554506)); } }
				}
				
				public static class Stop
				{
					//	designer:str/732K2
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554516)); } }
				}
				
				public static class SwitchInto
				{
					//	designer:str/732C2
					public static string No { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554508)); } }
					//	designer:str/732D2
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554509)); } }
					//	designer:str/732E2
					public static string Yes { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554510)); } }
				}
				
				public static class SwitchStep
				{
					//	designer:str/73272
					public static string No { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554503)); } }
					//	designer:str/73292
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554505)); } }
					//	designer:str/73282
					public static string Yes { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554504)); } }
				}
				
				public static class Underlined
				{
					//	designer:str/732A3
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554538)); } }
				}
				
				public static class Write
				{
					//	designer:str/732H2
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554513)); } }
					//	designer:str/732F2
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554511)); } }
				}
			}
			
			public static class Detail
			{
				public static class Display
				{
					//	designer:str/732J1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554483)); } }
					//	designer:str/732K1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554484)); } }
				}
				
				public static class PC
				{
					//	designer:str/732B1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554475)); } }
					//	designer:str/732C1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554476)); } }
				}
				
				public static class Periph
				{
					//	designer:str/732I1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554482)); } }
					//	designer:str/732H1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554481)); } }
				}
				
				public static class RAM
				{
					//	designer:str/732E1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554478)); } }
					//	designer:str/732D1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554477)); } }
				}
				
				public static class Reset
				{
					//	designer:str/732M1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554486)); } }
					//	designer:str/732L1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554485)); } }
				}
				
				public static class ROM
				{
					//	designer:str/732F1
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554479)); } }
					//	designer:str/732G1
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554480)); } }
				}
				
				public static class Title
				{
					//	designer:str/73291
					public static string Memory { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554473)); } }
					//	designer:str/732A1
					public static string Register { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554474)); } }
				}
			}
			
			public static class Dialog
			{
				public static class About
				{
					//	designer:str/732C3
					public static string Message { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554540)); } }
					public static class Web
					{
						//	designer:str/732I5
						public static string Dauphin { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554610)); } }
						//	designer:str/732H5
						public static string Epsitec { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554609)); } }
					}
				}
				
				public static class AutoSave
				{
					//	designer:str/732S2
					public static string Question1 { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554524)); } }
					//	designer:str/732T2
					public static string Question2 { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554525)); } }
				}
				
				public static class Close
				{
					//	designer:str/732K3
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554548)); } }
				}
				
				public static class CodeAccessor
				{
					public static class Shift
					{
						//	designer:str/732J4
						public static string Message { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554579)); } }
					}
				}
				
				public static class Download
				{
					//	designer:str/732H3
					public static string CurrentVersion { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554545)); } }
					//	designer:str/732I3
					public static string NoUpdate { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554546)); } }
					//	designer:str/732E3
					public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554542)); } }
					//	designer:str/732G3
					public static string UpdateAvailable { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554544)); } }
					//	designer:str/732J3
					public static string UpdateFound { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554547)); } }
					//	designer:str/732F3
					public static string UpToDate { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554543)); } }
				}
				
				public static class File
				{
					//	designer:str/732R2
					public static string Programs { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554523)); } }
				}
				
				public static class OK
				{
					//	designer:str/732D3
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554541)); } }
				}
				
				public static class Open
				{
					//	designer:str/732P2
					public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554521)); } }
				}
				
				public static class OpenCalm
				{
					//	designer:str/73223
					public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554530)); } }
				}
				
				public static class Save
				{
					//	designer:str/732Q2
					public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554522)); } }
				}
				
				public static class SaveCalm
				{
					//	designer:str/73233
					public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554531)); } }
				}
			}
			
			public static class Error
			{
				//	designer:str/732U2
				public static string Open { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554526)); } }
				//	designer:str/73213
				public static string Save { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554529)); } }
				public static class Read
				{
					//	designer:str/73203
					public static string Format { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554528)); } }
					//	designer:str/732V2
					public static string Version { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554527)); } }
				}
			}
			
			public static class Help
			{
				public static class Intro
				{
					//	designer:str/732D5
					public static string Content { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554605)); } }
				}
				
				public static class Notation
				{
					//	designer:str/732E5
					public static string Content { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554606)); } }
				}
				
				public static class Oper
				{
					//	designer:str/732F5
					public static string Content { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554607)); } }
				}
				
				public static class ROM
				{
					//	designer:str/732G5
					public static string Content { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554608)); } }
				}
			}
			
			public static class Path
			{
				//	designer:str/7312
				public static string ApplicationName { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (16777218)); } }
				//	designer:str/731
				public static string OriginalSamples { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (16777216)); } }
				//	designer:str/7311
				public static string UserSamples { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (16777217)); } }
			}
			
			public static class Processor
			{
				public static class Error
				{
					//	designer:str/732S4
					public static string AddressMissing { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554588)); } }
					//	designer:str/73215
					public static string Arguments { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554593)); } }
					//	designer:str/73225
					public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554594)); } }
					//	designer:str/73285
					public static string InstructionAddr { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554600)); } }
					//	designer:str/73245
					public static string InstructionListMany { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554596)); } }
					//	designer:str/73235
					public static string InstructionListOne { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554595)); } }
					//	designer:str/73265
					public static string InstructionRegister2 { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554598)); } }
					//	designer:str/73255
					public static string InstructionRegister4 { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554597)); } }
					//	designer:str/73275
					public static string InstructionVal { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554599)); } }
					//	designer:str/732U4
					public static string RegisterMissing { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554590)); } }
					//	designer:str/732V4
					public static string RegisterOrAddressMissing { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554591)); } }
					//	designer:str/732O4
					public static string ZeroArg { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554584)); } }
					public static class Byte
					{
						//	designer:str/732R4
						public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554587)); } }
					}
					
					public static class Swap
					{
						//	designer:str/73205
						public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554592)); } }
					}
					
					public static class Table
					{
						//	designer:str/732Q4
						public static string Generic { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554586)); } }
					}
				}
			}
			
			public static class Question
			{
				public static class Assembler
				{
					//	designer:str/73243
					public static string Do { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554532)); } }
					//	designer:str/73253
					public static string Ok { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554533)); } }
				}
			}
			
			public static class Quick
			{
				public static class Label
				{
					//	designer:str/73281
					public static string Default { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554472)); } }
				}
				
				public static class Title
				{
					//	designer:str/73271
					public static string Main { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554471)); } }
				}
			}
			
			public static class TabPage
			{
				public static class Bus
				{
					//	designer:str/7327
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554439)); } }
					//	designer:str/732C
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554444)); } }
				}
				
				public static class Calm
				{
					//	designer:str/732A
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554442)); } }
					//	designer:str/732G
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554448)); } }
				}
				
				public static class Code
				{
					//	designer:str/7329
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554441)); } }
					//	designer:str/732D
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554445)); } }
				}
				
				public static class Detail
				{
					//	designer:str/7328
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554440)); } }
					//	designer:str/732E
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554446)); } }
				}
				
				public static class Quick
				{
					//	designer:str/732B
					public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554443)); } }
					//	designer:str/732F
					public static string Tooltip { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554447)); } }
				}
				
				public static class Right
				{
					public static class Intro
					{
						//	designer:str/732C5
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554604)); } }
					}
					
					public static class Notation
					{
						//	designer:str/73295
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554601)); } }
					}
					
					public static class Oper
					{
						//	designer:str/732A5
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554602)); } }
					}
					
					public static class Program
					{
						//	designer:str/73283
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554536)); } }
					}
					
					public static class ROM
					{
						//	designer:str/732B5
						public static string Button { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554603)); } }
					}
				}
			}
			
			public static class Window
			{
				//	designer:str/73263
				public static string ApplicationTitle { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554534)); } }
				//	designer:str/73273
				public static string Comment { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554535)); } }
				//	designer:str/7321
				public static string Copyright { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554433)); } }
				//	designer:str/732
				public static string Title { get { return global::Epsitec.App.Dolphin.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (33554432)); } }
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(global::Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static global::Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}
		
		static Res()
		{
			Res.Initialize (typeof (Res), "App.Dolphin");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new global::Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static global::Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static global::Epsitec.Common.Support.ResourceManager _manager = global::Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 103;
	}
}
