<bundle>
<binary name='image.data' target='BaseIconsImage'/>
<data name='image.size'>256;256</data>
<data name='i.open'>0;240;16;16;0;2</data>
<data name='i.save'>16;240;16;16;0;2</data>
<data name='i.preview'>32;240;16;16;0;2</data>
<data name='i.print'>48;240;16;16;0;2</data>
<data name='i.cut'>64;240;16;16;0;2</data>
<data name='i.copy'>80;240;16;16;0;2</data>
<data name='i.paste'>96;240;16;16;0;2</data>
<data name='i.help'>112;240;16;16;0;2</data>
</bundle>
