<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="AccountsImport.DefaultTitle" id="K">Plan comptable</data>
  <data name="AccountsImport.ReadEmptyFilename" id="K1">Donnez un nom de plan comptable (fichier .cre)</data>
  <data name="AccountsLogic.InvalidDate" id="K2">Aucun plan comptable à cette date</data>
  <data name="AccountsLogic.AccountDoesNotExist" id="K3">Inconnu dans le plan comptable</data>
  <data name="AmortizationDefinition.Summary" id="K4">{0} {1} — Périodicité {2} — Arrondi {3} — Valeur résiduelle {4} — Au prorata {5}</data>
</bundle>