<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="Application.Name" id="A">Crésus Graphe {0} — version {1}</data>
  <data name="DataPicker.Title" id="A1">Sélection des données à représenter graphiquement</data>
  <data name="Message.FreePiccoloBecauseOfCompta" id="A2">&lt;i&gt;Note: licence active tant que le droit aux mises à jour pour &lt;b&gt;Crésus Comptabilité&lt;/b&gt; est valable (échéance: {0}).&lt;/i&gt;</data>
  <data name="Message.MoreThanPiccolo" id="A3">Souhaitez-vous faire plus avec Crésus Graphe ?&lt;br/&gt;Découvrez la &lt;a href="http://www.epsitec.ch/products/graphe/spec#PRO"&gt;version PRO&lt;/a&gt; !</data>
</bundle>