<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Cap.New" id="0">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Cmd.New" id="01">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Typ.New" id="02">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Val.New" id="03">&lt;s:data id="_0" f:Name="New" /&gt;</data>
</bundle>