<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Cap.New" id="0">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Cmd.FontBold" id="01">&lt;s:data id="_0" f:Name="FontBold" f:Icon="manifest:Epsitec.App.DocumentEditor.Images.FontBold.icon" f:Labels="{Collection {Text 'Gras'}}" /&gt;</data>
  <data name="Cmd.FontItalic" id="04">&lt;s:data id="_0" f:Name="FontItalic" f:Icon="manifest:Epsitec.App.DocumentEditor.Images.FontItalic.icon" f:Labels="{Collection {Text 'Italique'}}" /&gt;</data>
  <data name="Cmd.FontUnderline" id="05">&lt;s:data id="_0" f:Name="FontUnderline" f:Icon="manifest:Epsitec.App.DocumentEditor.Images.FontUnderline.icon" f:Labels="{Collection {Text 'Souligné'}}" /&gt;</data>
  <data name="Typ.New" id="02">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Val.New" id="03">&lt;s:data id="_0" f:Name="New" /&gt;</data>
</bundle>