<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Cap.Command.Cut" id="03">&lt;s:data id="_0" f:Description="Couper" f:Labels="{Collection {Text 'Couper'}}" /&gt;</data>
  <data name="Cap.Command.Copy" id="04">&lt;s:data id="_0" f:Description="Copier" f:Labels="{Collection {Text 'Copier'}}" /&gt;</data>
  <data name="Cap.Command.Paste" id="05">&lt;s:data id="_0" f:Description="Coller" f:Labels="{Collection {Text 'Coller'}}" /&gt;</data>
  <data name="Cap.Command.Delete" id="06">&lt;s:data id="_0" f:Description="Supprimer" f:Labels="{Collection {Text 'Supprimer'}}" /&gt;</data>
  <data name="Cap.Command.SelectAll" id="05">&lt;s:data id="_0" f:Description="Sélectionner tout" f:Labels="{Collection {Text 'Sélectionner tout'}}" /&gt;</data>
  <data name="Cmd.New" id="01"></data>
  <data name="Typ.New" id="02"></data>
</bundle>