<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Command.Cut" id="01">&lt;s:data id="_0" f:Description="[0000]" f:Labels="{Collection {Text '[0000]'}}" /&gt;</data>
  <data name="Command.Copy" id="02">&lt;s:data id="_0" f:Description="[0001]" f:Labels="{Collection {Text '[0001]'}}" /&gt;</data>
  <data name="Command.Paste" id="03">&lt;s:data id="_0" f:Description="[0002]" f:Labels="{Collection {Text '[0002]'}}" /&gt;</data>
  <data name="Command.Delete" id="04">&lt;s:data id="_0" f:Description="[0003]" f:Labels="{Collection {Text '[0003]'}}" /&gt;</data>
  <data name="Command.SelectAll" id="05">&lt;s:data id="_0" f:Description="[0004]" f:Labels="{Collection {Text '[0004]'}}" /&gt;</data>
</bundle>