<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="en">
  <data id="01">&lt;s:data id="_0" f:Description="Cut" f:Labels="{Collection {Text 'Cut'}}" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Description="Copy" f:Labels="{Collection {Text 'Copy'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Description="Paste" f:Labels="{Collection {Text 'Paste'}}" /&gt;</data>
  <data id="04">&lt;s:data id="_0" f:Description="Delete" f:Labels="{Collection {Text 'Delete'}, {Text 'Del.'}}" /&gt;</data>
  <data id="05">&lt;s:data id="_0" f:Description="Select all" f:Labels="{Collection {Text 'Select all'}, {Text 'Sel. all'}}" /&gt;</data>
  <data id="06">&lt;s:data id="_0" /&gt;</data>
  <data id="07">&lt;s:data id="_0" /&gt;</data>
</bundle>