<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="ProductName" id="1">Crésus Core (projet M)</data>
  <data name="Error.CannotConnectToLocalDatabase" id="A">{0} ne parvient pas à contacter la base de données.</data>
  <data name="Hint.Error.CannotConnectToLocalDatabase" id="A1">Vérifiez que le serveur Firebird est bien en exécution et que&lt;br/&gt;le pare-feu de Windows ne bloque pas ses accès.</data>
</bundle>