<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="en">
  <data id="01">&lt;s:data id="_0" f:Description="[4002]" f:Labels="{Collection {Text '[4003]'}, {Text '[4004]'}}" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Description="Pattern angle expressed in degrees." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Pattern angle'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Description="Quality coefficient." f:Labels="{Collection {Text 'Q'}}" /&gt;</data>
  <data id="04">&lt;s:data id="_0" f:Description="[4005]" f:Labels="{Collection {Text 'Text'}}" /&gt;</data>
  <data id="05">&lt;s:data id="_0" f:Description="One of Three" /&gt;</data>
  <data id="06">&lt;s:data id="_0" f:Description="None" /&gt;</data>
  <data id="07">&lt;s:data id="_0" f:Description="1st choice" /&gt;</data>
  <data id="08">&lt;s:data id="_0" f:Description="2nd choice" /&gt;</data>
  <data id="09">&lt;s:data id="_0" f:Description="3rd choice" /&gt;</data>
  <data id="0A">&lt;s:data id="_0" f:Description="Borrowed Text" /&gt;</data>
</bundle>
