<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="fr">
  <data id="01">&lt;s:data id="_0" f:Description="][Test]" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Description="Angle de rotation de la trame, exprimé en degrés." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Angle de la trame'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Description="Coefficient de Qualité." /&gt;</data>
</bundle>
