<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="en">
  <data id="01">&lt;s:data id="_0" f:Description="[4002]" f:Labels="{Collection {Text '[4003]'}, {Text '[4004]'}}" /&gt;</data>
  <data id="02" name="Cap.PatternAngle">&lt;s:data id="_0" f:Name="PatternAngle" f:Description="Pattern angle expressed in degrees." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Pattern angle'}}" /&gt;</data>
  <data id="03" name="Cap.QualityCoefficient">&lt;s:data id="_0" f:Name="QualityCoefficient" f:Description="Quality coefficient." f:Labels="{Collection {Text 'Q'}}" /&gt;</data>
  <data id="04">&lt;s:data id="_0" f:Description="[4005]" f:Labels="{Collection {Text 'Text'}}" /&gt;</data>
  <data id="05">&lt;s:data id="_0" f:Description="One of Three" /&gt;</data>
  <data id="06">&lt;s:data id="_0" f:Description="None" /&gt;</data>
  <data id="07">&lt;s:data id="_0" f:Description="1st choice" /&gt;</data>
  <data id="08">&lt;s:data id="_0" f:Description="2nd choice" /&gt;</data>
  <data id="09">&lt;s:data id="_0" f:Description="3rd choice" /&gt;</data>
  <data id="0A">&lt;s:data id="_0" f:Description="Borrowed Text" /&gt;</data>
  <data name="Cmd.Close" id="0B">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="2" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="Epsitec.Common.Widgets.Shortcut" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_2" /&gt;&lt;s:data id="_1" f:Name="Close" f:_2.Shortcuts="{Collection {ObjRef _2}}" f:Labels="{Collection {Text 'Fermer'}}" /&gt;&lt;s:data id="_2" f:KeyCode="FuncF4, ModifierControl" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
</bundle>
