<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="en">
  <data id="01">&lt;s:data id="_0" f:Description="[4002]" f:Labels="{Collection {Text '[4003]'}, {Text '[4004]'}}" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Description="Pattern angle expressed in degrees." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Pattern angle'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Description="Quality coefficient." f:Labels="{Collection {Text 'Q'}}" /&gt;</data>
</bundle>
