<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="String" name="Strings" culture="en">
  <data id="0">Druid - Hello, world</data>
  <data id="01">Druid - Good bye...</data>
  <data id="02">Text A</data>
  <data id="03">Text B</data>
  <data id="04">Text C</data>
  <data id="05">Text Property</data>
  <data name="Text1" id="06">Hello, world</data>
  <data name="Text2" id="07">Good bye...</data>
  <data id="08">&lt;null/&gt;</data>
</bundle>
