<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="String" name="Strings" culture="fr">
  <data id="0">Druid - Bonjour</data>
  <data id="01">Druid - Au revoir...</data>
  <data id="02">f:Description="Angle de rotation de la trame, exprimé en degrés." f:Labels="{Collection {Text 'A'}, {Text 'Angle'}, {Text 'Angle de la trame'}}"</data>
  <data id="03">f:Description="Coefficient de Qualité."</data>
</bundle>
