<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="en">
  <data id="K">Nb</data>
  <data id="K1">Quantity</data>
  <data id="K2">Additionnal quantities</data>
  <data id="K3">Article</data>
  <data id="K4">Description</data>
  <data id="K5">ET u.p.</data>
  <data id="K6">TTC u.p.</data>
  <data id="K7">Discount</data>
  <data id="K8">ET price</data>
  <data id="K9">TTC price</data>
  <data id="KA">VAT</data>
  <data id="KB">Total</data>
</bundle>