//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsitec.Data.Platform.Directories.Admin.Configuration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:directories/administration/v4/configuration", ConfigurationName="Directories.Admin.Configuration.ConfigurationSoap")]
    public interface ConfigurationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/administration/v4/configuration/SetRequestLimits", ReplyAction="*")]
        string SetRequestLimits(string requestLimitsParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/administration/v4/configuration/GetRequestLimits", ReplyAction="*")]
        string GetRequestLimits(string userOperationParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directories/administration/v4/configuration/Version", ReplyAction="*")]
        string Version();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfigurationSoapChannel : Epsitec.Data.Platform.Directories.Admin.Configuration.ConfigurationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationSoapClient : System.ServiceModel.ClientBase<Epsitec.Data.Platform.Directories.Admin.Configuration.ConfigurationSoap>, Epsitec.Data.Platform.Directories.Admin.Configuration.ConfigurationSoap {
        
        public ConfigurationSoapClient() {
        }
        
        public ConfigurationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SetRequestLimits(string requestLimitsParam) {
            return base.Channel.SetRequestLimits(requestLimitsParam);
        }
        
        public string GetRequestLimits(string userOperationParam) {
            return base.Channel.GetRequestLimits(userOperationParam);
        }
        
        public string Version() {
            return base.Channel.Version();
        }
    }
}
