<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Val.EnumValueCardinality.ZeroOrOne" id="A1">&lt;s:data id="_0" f:Name="ZeroOrOne" f:Labels="{Collection {Text 'Aucun ou un'}}" /&gt;</data>
  <data name="Val.EnumValueCardinality.ExactlyOne" id="A2">&lt;s:data id="_0" f:Name="ExactlyOne" f:Labels="{Collection {Text 'Exactement un'}}" /&gt;</data>
  <data name="Val.EnumValueCardinality.AtLeastOne" id="A3">&lt;s:data id="_0" f:Name="AtLeastOne" f:Labels="{Collection {Text 'Au moins un'}}" /&gt;</data>
  <data name="Val.EnumValueCardinality.Any" id="A4">&lt;s:data id="_0" f:Name="Any" f:Labels="{Collection {Text 'Zéro, un ou plusieurs'}}" /&gt;</data>
  <data name="Typ.EnumValueCardinality" id="A">&lt;s:type id="_1" s:name="*aT" /&gt;&lt;s:type id="_2" s:name="*eT" /&gt;&lt;s:data id="_0" f:Name="EnumValueCardinality" f:_1.SystemType="E:Epsitec.Cresus.Core.Library.EnumValueCardinality, Cresus.Core.Library" f:_2.EnumValues="{Collection {Text '0 [EVA4]'}, {Text '1 [EVA3]'}, {Text '2 [EVA2]'}, {Text '3 [EVA1]'}}" f:_1.DefaultValue="Epsitec.Cresus.Core.Library.EnumValueCardinality, Cresus.Core.Library/ZeroOrOne" f:Labels="{Collection {Text 'Cardinalité d&amp;amp;apos;une énumération'}}" /&gt;</data>
</bundle>