var epsitecConfig = {
  splash: 'images/Static/logo.png',
  featureActionPage: true,
  featureBigEntityBag: true,
  featureChat: true,
  featureContextualMenu: true,
  featureDisablePasswordCheck: true,
  featureDropZones: true,
  featureElasticSearch: true,
  featureEntityBag: true,
  featureFaq: true,
  featureMailing: true,
  featureNotifications: true,
  featureOfficeManagement: true,
  featureQueryBuilder: true,
  featureQuickSearch: true,
  featureSearch: true,
  featureStatusBar: true,
  featureWarnings: true
};
