//	Automatically generated by ResGenerator, on 28.09.2007
//	Do not edit manually.

namespace Epsitec.Common.Types
{
	public static class Res
	{
		//	Code mapping for 'Caption' resources
		
		public static class Types
		{
			public static readonly global::Epsitec.Common.Types.EnumType BindingMode = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 16));
			public static readonly global::Epsitec.Common.Types.EnumType CultureMapSource = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 1));
			public static readonly global::Epsitec.Common.Types.EnumType FieldMembership = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 29));
			public static readonly global::Epsitec.Common.Types.EnumType FieldOptions = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 0));
			public static readonly global::Epsitec.Common.Types.EnumType FieldRelation = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 22));
			public static readonly global::Epsitec.Common.Types.EnumType FieldSource = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 67));
			public static readonly global::Epsitec.Common.Types.EnumType StructuredTypeClass = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 33));
			public static readonly global::Epsitec.Common.Types.EnumType TimeResolution = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 43));
			public static readonly global::Epsitec.Common.Types.EnumType TypeCode = (global::Epsitec.Common.Types.EnumType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 63));
			public static class Default
			{
				public static readonly global::Epsitec.Common.Types.BooleanType Boolean = (global::Epsitec.Common.Types.BooleanType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 3));
				public static readonly global::Epsitec.Common.Types.DateType Date = (global::Epsitec.Common.Types.DateType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 17));
				public static readonly global::Epsitec.Common.Types.OtherType DateSpan = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 46));
				public static readonly global::Epsitec.Common.Types.DateTimeType DateTime = (global::Epsitec.Common.Types.DateTimeType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 19));
				public static readonly global::Epsitec.Common.Types.DecimalType Decimal = (global::Epsitec.Common.Types.DecimalType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 4));
				public static readonly global::Epsitec.Common.Types.OtherType DecimalRange = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 44));
				public static readonly global::Epsitec.Common.Types.DoubleType Double = (global::Epsitec.Common.Types.DoubleType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 5));
				public static readonly global::Epsitec.Common.Types.OtherType Druid = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 20));
				public static readonly global::Epsitec.Common.Types.IntegerType Integer = (global::Epsitec.Common.Types.IntegerType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 6));
				public static readonly global::Epsitec.Common.Types.LongIntegerType LongInteger = (global::Epsitec.Common.Types.LongIntegerType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 7));
				public static readonly global::Epsitec.Common.Types.OtherType Object = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 5));
				public static readonly global::Epsitec.Common.Types.StringType String = (global::Epsitec.Common.Types.StringType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 8));
				public static readonly global::Epsitec.Common.Types.OtherType SystemType = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 64));
				public static readonly global::Epsitec.Common.Types.TimeType Time = (global::Epsitec.Common.Types.TimeType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 18));
				public static readonly global::Epsitec.Common.Types.OtherType TimeSpan = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 45));
				public static readonly global::Epsitec.Common.Types.OtherType Void = (global::Epsitec.Common.Types.OtherType) global::Epsitec.Common.Types.TypeRosetta.CreateTypeObject (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 9));
			}
		}
		
		public static class Values
		{
			public static class BindingMode
			{
				public static global::Epsitec.Common.Types.Caption None { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 11)); } }
				public static global::Epsitec.Common.Types.Caption OneTime { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 12)); } }
				public static global::Epsitec.Common.Types.Caption OneWay { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 13)); } }
				public static global::Epsitec.Common.Types.Caption OneWayToSource { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 14)); } }
				public static global::Epsitec.Common.Types.Caption TwoWay { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 15)); } }
			}
			
			public static class CultureMapSource
			{
				public static global::Epsitec.Common.Types.Caption DynamicMerge { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 4)); } }
				public static global::Epsitec.Common.Types.Caption PatchModule { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 3)); } }
				public static global::Epsitec.Common.Types.Caption ReferenceModule { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 1, 2)); } }
			}
			
			public static class FieldMembership
			{
				public static global::Epsitec.Common.Types.Caption Inherited { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 28)); } }
				public static global::Epsitec.Common.Types.Caption Local { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 27)); } }
			}
			
			public static class FieldOptions
			{
				public static global::Epsitec.Common.Types.Caption None { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 25)); } }
			}
			
			public static class FieldRelation
			{
				public static global::Epsitec.Common.Types.Caption Collection { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 26)); } }
				public static global::Epsitec.Common.Types.Caption None { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 23)); } }
				public static global::Epsitec.Common.Types.Caption Reference { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 24)); } }
			}
			
			public static class FieldSource
			{
				public static global::Epsitec.Common.Types.Caption Expression { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 66)); } }
				public static global::Epsitec.Common.Types.Caption Value { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 65)); } }
			}
			
			public static class StructuredTypeClass
			{
				public static global::Epsitec.Common.Types.Caption Entity { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 31)); } }
				public static global::Epsitec.Common.Types.Caption Interface { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 32)); } }
				public static global::Epsitec.Common.Types.Caption None { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 30)); } }
			}
			
			public static class TimeResolution
			{
				public static global::Epsitec.Common.Types.Caption Days { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 39)); } }
				public static global::Epsitec.Common.Types.Caption Default { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 34)); } }
				public static global::Epsitec.Common.Types.Caption Hours { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 38)); } }
				public static global::Epsitec.Common.Types.Caption Milliseconds { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 35)); } }
				public static global::Epsitec.Common.Types.Caption Minutes { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 37)); } }
				public static global::Epsitec.Common.Types.Caption Months { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 41)); } }
				public static global::Epsitec.Common.Types.Caption Seconds { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 36)); } }
				public static global::Epsitec.Common.Types.Caption Weeks { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 40)); } }
				public static global::Epsitec.Common.Types.Caption Years { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 42)); } }
			}
			
			public static class TypeCode
			{
				public static global::Epsitec.Common.Types.Caption Binary { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 56)); } }
				public static global::Epsitec.Common.Types.Caption Boolean { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 48)); } }
				public static global::Epsitec.Common.Types.Caption Collection { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 61)); } }
				public static global::Epsitec.Common.Types.Caption Date { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 54)); } }
				public static global::Epsitec.Common.Types.Caption DateTime { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 53)); } }
				public static global::Epsitec.Common.Types.Caption Decimal { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 51)); } }
				public static global::Epsitec.Common.Types.Caption Double { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 52)); } }
				public static global::Epsitec.Common.Types.Caption Dynamic { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 60)); } }
				public static global::Epsitec.Common.Types.Caption Enum { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 58)); } }
				public static global::Epsitec.Common.Types.Caption Integer { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 49)); } }
				public static global::Epsitec.Common.Types.Caption Invalid { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 47)); } }
				public static global::Epsitec.Common.Types.Caption LongInteger { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 50)); } }
				public static global::Epsitec.Common.Types.Caption Other { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 62)); } }
				public static global::Epsitec.Common.Types.Caption String { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 57)); } }
				public static global::Epsitec.Common.Types.Caption Structured { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 59)); } }
				public static global::Epsitec.Common.Types.Caption Time { get { return Res._manager.GetCaption (new global::Epsitec.Common.Support.Druid (_moduleId, 0, 55)); } }
			}
		}
		
		//	Code mapping for 'String' resources
		
		public static class Strings
		{
			public static string Empty { get { return global::Epsitec.Common.Types.Res.Strings.GetText (global::Epsitec.Common.Support.Druid.FromFieldId (0)); } }
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(global::Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static global::Epsitec.Common.Support.ResourceBundle _stringsBundle = Res._manager.GetBundle ("Strings");
			#endregion
		}
		
		static Res()
		{
			Res.Initialize (typeof (Res), "Common.Types");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new global::Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static global::Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static global::Epsitec.Common.Support.ResourceManager _manager = global::Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 1;
	}
}
