<?xml version="1.0" encoding="utf-8" ?>
<!-- Ressources françaises pour le projet Common.Designer -->

<bundle type="String" name="DruidData" culture="fr">
  <data id="0" name="Application.Title">Éditeur de ressources</data>
  <data id="01" name="Button.Ok">D'accord</data>
  <data id="02" name="Button.Cancel">Annuler</data>
  <data id="03" name="Button.Yes">Oui</data>
  <data id="04" name="Button.No">Non</data>
</bundle>
