<?xml version="1.0" encoding="utf-8" ?>
<!-- Ressources anglaises pour le projet Common.Designer -->

<bundle type="String" name="DruidData" culture="en">
  <data id="0" name="Application.Title">Resource Designer</data>
  <data id="01" name="Button.Ok">OK</data>
  <data id="02" name="Button.Cancel">Cancel</data>
  <data id="03" name="Button.Yes">Yes</data>
  <data id="04" name="Button.No">No</data>
</bundle>
