<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data id="15" about="Juste pour les essais (patché)...">&lt;s:data id="_0" f:Description="Description patchée pour Test1" /&gt;</data>
  <data name="Fld.Shortcut.X" id="1E">&lt;s:data id="_0" f:Name="X" /&gt;</data>
  <data id="0Q">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="3" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="*aT" /&gt;&lt;s:type id="_3" s:name="*S" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_3" /&gt;&lt;s:data id="_1" f:_2.ComplexType="{ObjRef _2}" /&gt;&lt;s:data id="_2" f:Class="Entity" f:SerializedDesignerLayouts="{Null}" f:Fields="{Collection {Text '[701E];&amp;lt;invalid&amp;gt;;1;[701E]'}}" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
  <data name="Cap.TestCaption4" id="1K">&lt;s:data id="_0" f:Name="TestCaption4" f:Description="Défini dans le module de patch seulement" f:Labels="{Collection {Text 'Patch seul'}}" /&gt;</data>
  <data id="18" about="Commentaire que dans le patch">&lt;null/&gt;</data>
</bundle>