<bundle>
<binary name='image.data' target='bitmap'/>
<data name='image.size'>960;48</data>
<data name='i.new'>0;24;24;24;0;6</data>
<data name='i.open'>24;24;24;24;0;6</data>
<data name='i.save'>48;24;24;24;0;6</data>
<data name='i.cut'>96;24;24;24;0;6</data>
<data name='i.copy'>120;24;24;24;0;6</data>
<data name='i.paste'>144;24;24;24;0;6</data>
<data name='i.back'>408;24;24;24;0;6</data>
<data name='i.forward'>432;24;24;24;0;6</data>
</bundle>
