<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="String">
	<data name='title.Dialog.Open'>Open..</data>
	<data name='title.Dialog.Save'>Save..</data>
	<data name='label.OK'>OK</data>
	<data name='label.Hello'><![CDATA[Hello <i>world</i>&nbsp;!]]></data>
	<data name='title.MainWindow'>Crésus Réseau</data>
	<data name='title.SettingsWindow'>Settings</data>
	<data name='title.AboutWindow'>About Crésus Réseau</data>
</bundle>
