//	Automatically generated by ResGenerator, on 17.06.2006 17:12:11
//	Do not edit manually.

namespace Epsitec.Common.Widgets
{
	public sealed class Res
	{
		public sealed class Strings
		{
			public sealed class AbstractTextField
			{
				public sealed class Menu
				{
					public static string Copy { get { return GetText ("Strings", "$01"); } }
					public static string Cut { get { return GetText ("Strings", "$0"); } }
					public static string Delete { get { return GetText ("Strings", "$03"); } }
					public static string Paste { get { return GetText ("Strings", "$02"); } }
					public static string SelectAll { get { return GetText ("Strings", "$04"); } }
				}
			}
			
			public sealed class ColorPalette
			{
				public static string OpenPalette { get { return GetText ("Strings", "$0B"); } }
				public static string Options { get { return GetText ("Strings", "$05"); } }
				public static string PaletteDark { get { return GetText ("Strings", "$09"); } }
				public static string PaletteDefault { get { return GetText ("Strings", "$06"); } }
				public static string PaletteGray { get { return GetText ("Strings", "$0A"); } }
				public static string PaletteLight { get { return GetText ("Strings", "$08"); } }
				public static string PaletteRainbow { get { return GetText ("Strings", "$07"); } }
				public static string SavePalette { get { return GetText ("Strings", "$0C"); } }
			}
			
			public sealed class ColorSelector
			{
				public static string Close { get { return GetText ("Strings", "$081"); } }
				public static string LongAlpha { get { return GetText ("Strings", "$0T"); } }
				public static string LongBlack { get { return GetText ("Strings", "$041"); } }
				public static string LongBlue { get { return GetText ("Strings", "$0S"); } }
				public static string LongCyan { get { return GetText ("Strings", "$011"); } }
				public static string LongGray { get { return GetText ("Strings", "$051"); } }
				public static string LongGreen { get { return GetText ("Strings", "$0R"); } }
				public static string LongHexa { get { return GetText ("Strings", "$061"); } }
				public static string LongHue { get { return GetText ("Strings", "$0U"); } }
				public static string LongMagenta { get { return GetText ("Strings", "$021"); } }
				public static string LongRed { get { return GetText ("Strings", "$0Q"); } }
				public static string LongSaturation { get { return GetText ("Strings", "$0V"); } }
				public static string LongValue { get { return GetText ("Strings", "$001"); } }
				public static string LongYellow { get { return GetText ("Strings", "$031"); } }
				public static string Picker { get { return GetText ("Strings", "$071"); } }
				public static string ShortAlpha { get { return GetText ("Strings", "$0G"); } }
				public static string ShortBlack { get { return GetText ("Strings", "$0N"); } }
				public static string ShortBlue { get { return GetText ("Strings", "$0F"); } }
				public static string ShortCyan { get { return GetText ("Strings", "$0K"); } }
				public static string ShortGray { get { return GetText ("Strings", "$0O"); } }
				public static string ShortGreen { get { return GetText ("Strings", "$0E"); } }
				public static string ShortHexa { get { return GetText ("Strings", "$0P"); } }
				public static string ShortHue { get { return GetText ("Strings", "$0H"); } }
				public static string ShortMagenta { get { return GetText ("Strings", "$0L"); } }
				public static string ShortRed { get { return GetText ("Strings", "$0D"); } }
				public static string ShortSaturation { get { return GetText ("Strings", "$0I"); } }
				public static string ShortValue { get { return GetText ("Strings", "$0J"); } }
				public static string ShortYellow { get { return GetText ("Strings", "$0M"); } }
				public sealed class ColorSpace
				{
					public static string Cmyk { get { return GetText ("Strings", "$0A1"); } }
					public static string Gray { get { return GetText ("Strings", "$0B1"); } }
					public static string Rgb { get { return GetText ("Strings", "$091"); } }
				}
			}
			
			public sealed class Dialog
			{
				public sealed class Button
				{
					public static string Cancel { get { return GetText ("Strings", "$0E1"); } }
					public static string No { get { return GetText ("Strings", "$0D1"); } }
					public static string OK { get { return GetText ("Strings", "$0F1"); } }
					public static string Yes { get { return GetText ("Strings", "$0C1"); } }
				}
			}
			
			public sealed class EditArray
			{
				public static string Delete { get { return GetText ("Strings", "$0L1"); } }
				public static string InsertAfter { get { return GetText ("Strings", "$0K1"); } }
				public static string InsertBefore { get { return GetText ("Strings", "$0J1"); } }
				public static string MoveDown { get { return GetText ("Strings", "$0N1"); } }
				public static string MoveUp { get { return GetText ("Strings", "$0M1"); } }
				public static string StartEdition { get { return GetText ("Strings", "$0H1"); } }
				public static string StartReadOnly { get { return GetText ("Strings", "$0G1"); } }
				public static string StartSearch { get { return GetText ("Strings", "$0I1"); } }
			}
			
			public sealed class IconButtonsCombo
			{
				public static string Menu { get { return GetText ("Strings", "$0Q1"); } }
				public static string Next { get { return GetText ("Strings", "$0P1"); } }
				public static string Prev { get { return GetText ("Strings", "$0O1"); } }
			}
			
			public sealed class TextNavigator
			{
				public sealed class Action
				{
					public static string Delete { get { return GetText ("Strings", "$0T1"); } }
					public static string Insert { get { return GetText ("Strings", "$0S1"); } }
					public static string Modify { get { return GetText ("Strings", "$0R1"); } }
					public static string Style { get { return GetText ("Strings", "$0U1"); } }
					public static string Tab { get { return GetText ("Strings", "$0V1"); } }
				}
			}
			
			public sealed class TextRuler
			{
				public static string Bold { get { return GetText ("Strings", "$062"); } }
				public static string ButtonBold { get { return GetText ("Strings", "$032"); } }
				public static string ButtonItalic { get { return GetText ("Strings", "$042"); } }
				public static string ButtonUnderlined { get { return GetText ("Strings", "$052"); } }
				public static string Color { get { return GetText ("Strings", "$0A2"); } }
				public static string DefaultColor { get { return GetText ("Strings", "$092"); } }
				public static string FontDefault { get { return GetText ("Strings", "$0F2"); } }
				public static string FontName { get { return GetText ("Strings", "$012"); } }
				public static string FontSize { get { return GetText ("Strings", "$022"); } }
				public static string Italic { get { return GetText ("Strings", "$072"); } }
				public static string ListFix { get { return GetText ("Strings", "$0C2"); } }
				public static string ListNum { get { return GetText ("Strings", "$0B2"); } }
				public static string Tab { get { return GetText ("Strings", "$002"); } }
				public static string Underlined { get { return GetText ("Strings", "$082"); } }
				public sealed class Tooltip
				{
					public static string Deleted { get { return GetText ("Strings", "$0E2"); } }
					public static string Unit { get { return GetText ("Strings", "$0D2"); } }
				}
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _bundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialise(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.DefineDefaultModuleName (name);
		}
		
		public static Epsitec.Common.Support.ResourceManager Manager
		{
			get { return _manager; }
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
	}
}
