//	Automatically generated by ResGenerator, on 26.05.2006 11:15:21
//	Do not edit manually.

namespace Epsitec.Common.Widgets
{
	public sealed class Res
	{
		public sealed class Strings
		{
			public sealed class AbstractTextField
			{
				public sealed class Menu
				{
					public static string Copy { get { return GetText ("Strings", "AbstractTextField", "Menu", "Copy"); } }
					public static string Cut { get { return GetText ("Strings", "AbstractTextField", "Menu", "Cut"); } }
					public static string Delete { get { return GetText ("Strings", "AbstractTextField", "Menu", "Delete"); } }
					public static string Paste { get { return GetText ("Strings", "AbstractTextField", "Menu", "Paste"); } }
					public static string SelectAll { get { return GetText ("Strings", "AbstractTextField", "Menu", "SelectAll"); } }
				}
			}
			
			public sealed class ColorPalette
			{
				public static string OpenPalette { get { return GetText ("Strings", "ColorPalette", "OpenPalette"); } }
				public static string Options { get { return GetText ("Strings", "ColorPalette", "Options"); } }
				public static string PaletteDark { get { return GetText ("Strings", "ColorPalette", "PaletteDark"); } }
				public static string PaletteDefault { get { return GetText ("Strings", "ColorPalette", "PaletteDefault"); } }
				public static string PaletteGray { get { return GetText ("Strings", "ColorPalette", "PaletteGray"); } }
				public static string PaletteLight { get { return GetText ("Strings", "ColorPalette", "PaletteLight"); } }
				public static string PaletteRainbow { get { return GetText ("Strings", "ColorPalette", "PaletteRainbow"); } }
				public static string SavePalette { get { return GetText ("Strings", "ColorPalette", "SavePalette"); } }
			}
			
			public sealed class ColorSelector
			{
				public static string Close { get { return GetText ("Strings", "ColorSelector", "Close"); } }
				public static string LongAlpha { get { return GetText ("Strings", "ColorSelector", "LongAlpha"); } }
				public static string LongBlack { get { return GetText ("Strings", "ColorSelector", "LongBlack"); } }
				public static string LongBlue { get { return GetText ("Strings", "ColorSelector", "LongBlue"); } }
				public static string LongCyan { get { return GetText ("Strings", "ColorSelector", "LongCyan"); } }
				public static string LongGray { get { return GetText ("Strings", "ColorSelector", "LongGray"); } }
				public static string LongGreen { get { return GetText ("Strings", "ColorSelector", "LongGreen"); } }
				public static string LongHexa { get { return GetText ("Strings", "ColorSelector", "LongHexa"); } }
				public static string LongHue { get { return GetText ("Strings", "ColorSelector", "LongHue"); } }
				public static string LongMagenta { get { return GetText ("Strings", "ColorSelector", "LongMagenta"); } }
				public static string LongRed { get { return GetText ("Strings", "ColorSelector", "LongRed"); } }
				public static string LongSaturation { get { return GetText ("Strings", "ColorSelector", "LongSaturation"); } }
				public static string LongValue { get { return GetText ("Strings", "ColorSelector", "LongValue"); } }
				public static string LongYellow { get { return GetText ("Strings", "ColorSelector", "LongYellow"); } }
				public static string Picker { get { return GetText ("Strings", "ColorSelector", "Picker"); } }
				public static string ShortAlpha { get { return GetText ("Strings", "ColorSelector", "ShortAlpha"); } }
				public static string ShortBlack { get { return GetText ("Strings", "ColorSelector", "ShortBlack"); } }
				public static string ShortBlue { get { return GetText ("Strings", "ColorSelector", "ShortBlue"); } }
				public static string ShortCyan { get { return GetText ("Strings", "ColorSelector", "ShortCyan"); } }
				public static string ShortGray { get { return GetText ("Strings", "ColorSelector", "ShortGray"); } }
				public static string ShortGreen { get { return GetText ("Strings", "ColorSelector", "ShortGreen"); } }
				public static string ShortHexa { get { return GetText ("Strings", "ColorSelector", "ShortHexa"); } }
				public static string ShortHue { get { return GetText ("Strings", "ColorSelector", "ShortHue"); } }
				public static string ShortMagenta { get { return GetText ("Strings", "ColorSelector", "ShortMagenta"); } }
				public static string ShortRed { get { return GetText ("Strings", "ColorSelector", "ShortRed"); } }
				public static string ShortSaturation { get { return GetText ("Strings", "ColorSelector", "ShortSaturation"); } }
				public static string ShortValue { get { return GetText ("Strings", "ColorSelector", "ShortValue"); } }
				public static string ShortYellow { get { return GetText ("Strings", "ColorSelector", "ShortYellow"); } }
				public sealed class ColorSpace
				{
					public static string Cmyk { get { return GetText ("Strings", "ColorSelector", "ColorSpace", "Cmyk"); } }
					public static string Gray { get { return GetText ("Strings", "ColorSelector", "ColorSpace", "Gray"); } }
					public static string Rgb { get { return GetText ("Strings", "ColorSelector", "ColorSpace", "Rgb"); } }
				}
			}
			
			public sealed class Dialog
			{
				public sealed class Button
				{
					public static string Cancel { get { return GetText ("Strings", "Dialog", "Button", "Cancel"); } }
					public static string No { get { return GetText ("Strings", "Dialog", "Button", "No"); } }
					public static string OK { get { return GetText ("Strings", "Dialog", "Button", "OK"); } }
					public static string Yes { get { return GetText ("Strings", "Dialog", "Button", "Yes"); } }
				}
			}
			
			public sealed class EditArray
			{
				public static string Delete { get { return GetText ("Strings", "EditArray", "Delete"); } }
				public static string InsertAfter { get { return GetText ("Strings", "EditArray", "InsertAfter"); } }
				public static string InsertBefore { get { return GetText ("Strings", "EditArray", "InsertBefore"); } }
				public static string MoveDown { get { return GetText ("Strings", "EditArray", "MoveDown"); } }
				public static string MoveUp { get { return GetText ("Strings", "EditArray", "MoveUp"); } }
				public static string StartEdition { get { return GetText ("Strings", "EditArray", "StartEdition"); } }
				public static string StartReadOnly { get { return GetText ("Strings", "EditArray", "StartReadOnly"); } }
				public static string StartSearch { get { return GetText ("Strings", "EditArray", "StartSearch"); } }
			}
			
			public sealed class IconButtonsCombo
			{
				public static string Menu { get { return GetText ("Strings", "IconButtonsCombo", "Menu"); } }
				public static string Next { get { return GetText ("Strings", "IconButtonsCombo", "Next"); } }
				public static string Prev { get { return GetText ("Strings", "IconButtonsCombo", "Prev"); } }
			}
			
			public sealed class TextNavigator
			{
				public sealed class Action
				{
					public static string Delete { get { return GetText ("Strings", "TextNavigator", "Action", "Delete"); } }
					public static string Insert { get { return GetText ("Strings", "TextNavigator", "Action", "Insert"); } }
					public static string Modify { get { return GetText ("Strings", "TextNavigator", "Action", "Modify"); } }
					public static string Style { get { return GetText ("Strings", "TextNavigator", "Action", "Style"); } }
					public static string Tab { get { return GetText ("Strings", "TextNavigator", "Action", "Tab"); } }
				}
			}
			
			public sealed class TextRuler
			{
				public static string Bold { get { return GetText ("Strings", "TextRuler", "Bold"); } }
				public static string ButtonBold { get { return GetText ("Strings", "TextRuler", "ButtonBold"); } }
				public static string ButtonItalic { get { return GetText ("Strings", "TextRuler", "ButtonItalic"); } }
				public static string ButtonUnderlined { get { return GetText ("Strings", "TextRuler", "ButtonUnderlined"); } }
				public static string Color { get { return GetText ("Strings", "TextRuler", "Color"); } }
				public static string DefaultColor { get { return GetText ("Strings", "TextRuler", "DefaultColor"); } }
				public static string FontDefault { get { return GetText ("Strings", "TextRuler", "FontDefault"); } }
				public static string FontName { get { return GetText ("Strings", "TextRuler", "FontName"); } }
				public static string FontSize { get { return GetText ("Strings", "TextRuler", "FontSize"); } }
				public static string Italic { get { return GetText ("Strings", "TextRuler", "Italic"); } }
				public static string ListFix { get { return GetText ("Strings", "TextRuler", "ListFix"); } }
				public static string ListNum { get { return GetText ("Strings", "TextRuler", "ListNum"); } }
				public static string Tab { get { return GetText ("Strings", "TextRuler", "Tab"); } }
				public static string Underlined { get { return GetText ("Strings", "TextRuler", "Underlined"); } }
				public sealed class Tooltip
				{
					public static string Deleted { get { return GetText ("Strings", "TextRuler", "Tooltip", "Deleted"); } }
					public static string Unit { get { return GetText ("Strings", "TextRuler", "Tooltip", "Unit"); } }
				}
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _bundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialise(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.SetupApplication (name);
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
	}
}
