//	Automatically generated by ResGenerator, on 09.10.2006 16:38:48
//	Do not edit manually.

namespace Epsitec.Common.Widgets
{
	public static class Res
	{
		public static class Commands
		{
			public static readonly Epsitec.Common.Widgets.Command Copy = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (Epsitec.Common.Support.Druid.FromModuleDruid (_moduleId, 2)));
			public static readonly Epsitec.Common.Widgets.Command Cut = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (Epsitec.Common.Support.Druid.FromModuleDruid (_moduleId, 1)));
			public static readonly Epsitec.Common.Widgets.Command Delete = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (Epsitec.Common.Support.Druid.FromModuleDruid (_moduleId, 4)));
			public static readonly Epsitec.Common.Widgets.Command Paste = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (Epsitec.Common.Support.Druid.FromModuleDruid (_moduleId, 3)));
			public static readonly Epsitec.Common.Widgets.Command SelectAll = Epsitec.Common.Widgets.Command.Get (Epsitec.Common.Support.Druid.FromLong (Epsitec.Common.Support.Druid.FromModuleDruid (_moduleId, 5)));
			
			internal static void _Initialize()
			{
			}
		}
		public static class Strings
		{
			public static class AbstractTextField
			{
				public static class Menu
				{
					public static string Copy { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (1)); } }
					public static string Cut { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (0)); } }
					public static string Delete { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (3)); } }
					public static string Paste { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (2)); } }
					public static string SelectAll { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (4)); } }
				}
			}
			
			public static class ColorPalette
			{
				public static string OpenPalette { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (11)); } }
				public static string Options { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (5)); } }
				public static string PaletteDark { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (9)); } }
				public static string PaletteDefault { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (6)); } }
				public static string PaletteGray { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (10)); } }
				public static string PaletteLight { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (8)); } }
				public static string PaletteRainbow { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (7)); } }
				public static string SavePalette { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (12)); } }
			}
			
			public static class ColorSelector
			{
				public static string Close { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (40)); } }
				public static string LongAlpha { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (29)); } }
				public static string LongBlack { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (36)); } }
				public static string LongBlue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (28)); } }
				public static string LongCyan { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (33)); } }
				public static string LongGray { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (37)); } }
				public static string LongGreen { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (27)); } }
				public static string LongHexa { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (38)); } }
				public static string LongHue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (30)); } }
				public static string LongMagenta { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (34)); } }
				public static string LongRed { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (26)); } }
				public static string LongSaturation { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (31)); } }
				public static string LongValue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (32)); } }
				public static string LongYellow { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (35)); } }
				public static string Picker { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (39)); } }
				public static string ShortAlpha { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (16)); } }
				public static string ShortBlack { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (23)); } }
				public static string ShortBlue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (15)); } }
				public static string ShortCyan { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (20)); } }
				public static string ShortGray { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (24)); } }
				public static string ShortGreen { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (14)); } }
				public static string ShortHexa { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (25)); } }
				public static string ShortHue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (17)); } }
				public static string ShortMagenta { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (21)); } }
				public static string ShortRed { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (13)); } }
				public static string ShortSaturation { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (18)); } }
				public static string ShortValue { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (19)); } }
				public static string ShortYellow { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (22)); } }
				public static class ColorSpace
				{
					public static string Cmyk { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (42)); } }
					public static string Gray { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (43)); } }
					public static string Rgb { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (41)); } }
				}
			}
			
			public static class Dialog
			{
				public static class Button
				{
					public static string Cancel { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (46)); } }
					public static string No { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (45)); } }
					public static string OK { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (47)); } }
					public static string Yes { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (44)); } }
				}
			}
			
			public static class EditArray
			{
				public static string Delete { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (53)); } }
				public static string InsertAfter { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (52)); } }
				public static string InsertBefore { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (51)); } }
				public static string MoveDown { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (55)); } }
				public static string MoveUp { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (54)); } }
				public static string StartEdition { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (49)); } }
				public static string StartReadOnly { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (48)); } }
				public static string StartSearch { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (50)); } }
			}
			
			public static class IconButtonsCombo
			{
				public static string Menu { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (58)); } }
				public static string Next { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (57)); } }
				public static string Prev { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (56)); } }
			}
			
			public static class Shortcut
			{
				public static class Template
				{
					public static string TextWithShortcut { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (84)); } }
				}
			}
			
			public static class ShortcutEditor
			{
				public static class Code
				{
					public static string None { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (81)); } }
					public static string Tooltip { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (83)); } }
				}
				
				public static class Modifier
				{
					public static string None { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (80)); } }
					public static string Tooltip { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (82)); } }
				}
			}
			
			public static class TextNavigator
			{
				public static class Action
				{
					public static string Delete { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (61)); } }
					public static string Insert { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (60)); } }
					public static string Modify { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (59)); } }
					public static string Style { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (62)); } }
					public static string Tab { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (63)); } }
				}
			}
			
			public static class TextRuler
			{
				public static string Bold { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (70)); } }
				public static string ButtonBold { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (67)); } }
				public static string ButtonItalic { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (68)); } }
				public static string ButtonUnderlined { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (69)); } }
				public static string Color { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (74)); } }
				public static string DefaultColor { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (73)); } }
				public static string FontDefault { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (79)); } }
				public static string FontName { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (65)); } }
				public static string FontSize { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (66)); } }
				public static string Italic { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (71)); } }
				public static string ListFix { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (76)); } }
				public static string ListNum { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (75)); } }
				public static string Tab { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (64)); } }
				public static string Underlined { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (72)); } }
				public static class Tooltip
				{
					public static string Deleted { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (78)); } }
					public static string Unit { get { return Epsitec.Common.Widgets.Res.Strings.GetText (Epsitec.Common.Support.Druid.FromFieldId (77)); } }
				}
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _stringsBundle[field].AsString;
			}
			private static string GetText(Epsitec.Common.Support.Druid druid)
			{
				return _stringsBundle[druid].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _stringsBundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialize(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.DefineDefaultModuleName (name);
			Commands._Initialize ();
		}
		
		public static Epsitec.Common.Support.ResourceManager Manager
		{
			get { return _manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
		private static int _moduleId = 0;
	}
}
