<?xml version="1.0" encoding="utf-8" ?>
<!-- Save as UTF-8 -->

<bundle type="Caption" name="Captions" culture="en">
  <data id="01">&lt;s:data id="_0" f:Name="U1" f:Description="Entity Number 1 (user)" f:Labels="{Collection {Text 'UserEntity1'}}" /&gt;</data>
  <data id="02">&lt;s:data id="_0" f:Name="V" f:Labels="{Collection {Text 'Field V'}}" /&gt;</data>
  <data id="03">&lt;s:data id="_0" f:Name="W" f:Labels="{Collection {Text 'Field W'}}" /&gt;</data>
</bundle>
