//	Automatically generated by ResGenerator, on 11.08.2006 15:55:05
//	Do not edit manually.

namespace Epsitec.Common.Designer
{
	public sealed class Res
	{
		public sealed class Strings
		{
			public sealed class Action
			{
				public static string AccessFirst { get { return GetText ("Strings", "Action", "AccessFirst"); } }
				public static string AccessLast { get { return GetText ("Strings", "Action", "AccessLast"); } }
				public static string AccessNext { get { return GetText ("Strings", "Action", "AccessNext"); } }
				public static string AccessPrev { get { return GetText ("Strings", "Action", "AccessPrev"); } }
				public static string AdjustHeight { get { return GetText ("Strings", "Action", "AdjustHeight"); } }
				public static string AdjustWidth { get { return GetText ("Strings", "Action", "AdjustWidth"); } }
				public static string AlignBaseLine { get { return GetText ("Strings", "Action", "AlignBaseLine"); } }
				public static string AlignBottom { get { return GetText ("Strings", "Action", "AlignBottom"); } }
				public static string AlignCenterX { get { return GetText ("Strings", "Action", "AlignCenterX"); } }
				public static string AlignCenterY { get { return GetText ("Strings", "Action", "AlignCenterY"); } }
				public static string AlignGrid { get { return GetText ("Strings", "Action", "AlignGrid"); } }
				public static string AlignLeft { get { return GetText ("Strings", "Action", "AlignLeft"); } }
				public static string AlignRight { get { return GetText ("Strings", "Action", "AlignRight"); } }
				public static string AlignTop { get { return GetText ("Strings", "Action", "AlignTop"); } }
				public static string Check { get { return GetText ("Strings", "Action", "Check"); } }
				public static string Close { get { return GetText ("Strings", "Action", "Close"); } }
				public static string CloseAll { get { return GetText ("Strings", "Action", "CloseAll"); } }
				public static string Copy { get { return GetText ("Strings", "Action", "Copy"); } }
				public static string Create { get { return GetText ("Strings", "Action", "Create"); } }
				public static string Cut { get { return GetText ("Strings", "Action", "Cut"); } }
				public static string Delete { get { return GetText ("Strings", "Action", "Delete"); } }
				public static string DeleteCulture { get { return GetText ("Strings", "Action", "DeleteCulture"); } }
				public static string Down { get { return GetText ("Strings", "Action", "Down"); } }
				public static string Duplicate { get { return GetText ("Strings", "Action", "Duplicate"); } }
				public static string Filter { get { return GetText ("Strings", "Action", "Filter"); } }
				public static string FontBold { get { return GetText ("Strings", "Action", "FontBold"); } }
				public static string FontItalic { get { return GetText ("Strings", "Action", "FontItalic"); } }
				public static string FontUnderlined { get { return GetText ("Strings", "Action", "FontUnderlined"); } }
				public static string Glyphs { get { return GetText ("Strings", "Action", "Glyphs"); } }
				public static string LastFiles { get { return GetText ("Strings", "Action", "LastFiles"); } }
				public static string ModificationAll { get { return GetText ("Strings", "Action", "ModificationAll"); } }
				public static string ModificationClear { get { return GetText ("Strings", "Action", "ModificationClear"); } }
				public static string ModificationNext { get { return GetText ("Strings", "Action", "ModificationNext"); } }
				public static string ModificationPrev { get { return GetText ("Strings", "Action", "ModificationPrev"); } }
				public static string MoveDown { get { return GetText ("Strings", "Action", "MoveDown"); } }
				public static string MoveLeft { get { return GetText ("Strings", "Action", "MoveLeft"); } }
				public static string MoveRight { get { return GetText ("Strings", "Action", "MoveRight"); } }
				public static string MoveUp { get { return GetText ("Strings", "Action", "MoveUp"); } }
				public static string New { get { return GetText ("Strings", "Action", "New"); } }
				public static string NewCulture { get { return GetText ("Strings", "Action", "NewCulture"); } }
				public static string ObjectButton { get { return GetText ("Strings", "Action", "ObjectButton"); } }
				public static string ObjectGroup { get { return GetText ("Strings", "Action", "ObjectGroup"); } }
				public static string ObjectGroupBox { get { return GetText ("Strings", "Action", "ObjectGroupBox"); } }
				public static string ObjectHLine { get { return GetText ("Strings", "Action", "ObjectHLine"); } }
				public static string ObjectStatic { get { return GetText ("Strings", "Action", "ObjectStatic"); } }
				public static string ObjectText { get { return GetText ("Strings", "Action", "ObjectText"); } }
				public static string ObjectVLine { get { return GetText ("Strings", "Action", "ObjectVLine"); } }
				public static string Open { get { return GetText ("Strings", "Action", "Open"); } }
				public static string OrderDownAll { get { return GetText ("Strings", "Action", "OrderDownAll"); } }
				public static string OrderDownOne { get { return GetText ("Strings", "Action", "OrderDownOne"); } }
				public static string OrderUpAll { get { return GetText ("Strings", "Action", "OrderUpAll"); } }
				public static string OrderUpOne { get { return GetText ("Strings", "Action", "OrderUpOne"); } }
				public static string PanelDelete { get { return GetText ("Strings", "Action", "PanelDelete"); } }
				public static string PanelDeselectAll { get { return GetText ("Strings", "Action", "PanelDeselectAll"); } }
				public static string PanelDuplicate { get { return GetText ("Strings", "Action", "PanelDuplicate"); } }
				public static string PanelRun { get { return GetText ("Strings", "Action", "PanelRun"); } }
				public static string PanelSelectAll { get { return GetText ("Strings", "Action", "PanelSelectAll"); } }
				public static string PanelSelectInvert { get { return GetText ("Strings", "Action", "PanelSelectInvert"); } }
				public static string PanelShowAttachment { get { return GetText ("Strings", "Action", "PanelShowAttachment"); } }
				public static string PanelShowConstrain { get { return GetText ("Strings", "Action", "PanelShowConstrain"); } }
				public static string PanelShowExpand { get { return GetText ("Strings", "Action", "PanelShowExpand"); } }
				public static string PanelShowGrid { get { return GetText ("Strings", "Action", "PanelShowGrid"); } }
				public static string PanelShowTabIndex { get { return GetText ("Strings", "Action", "PanelShowTabIndex"); } }
				public static string PanelShowZOrder { get { return GetText ("Strings", "Action", "PanelShowZOrder"); } }
				public static string Paste { get { return GetText ("Strings", "Action", "Paste"); } }
				public static string Quit { get { return GetText ("Strings", "Action", "Quit"); } }
				public static string Save { get { return GetText ("Strings", "Action", "Save"); } }
				public static string SaveAs { get { return GetText ("Strings", "Action", "SaveAs"); } }
				public static string Search { get { return GetText ("Strings", "Action", "Search"); } }
				public static string SearchNext { get { return GetText ("Strings", "Action", "SearchNext"); } }
				public static string SearchPrev { get { return GetText ("Strings", "Action", "SearchPrev"); } }
				public static string TabIndexClear { get { return GetText ("Strings", "Action", "TabIndexClear"); } }
				public static string TabIndexFirst { get { return GetText ("Strings", "Action", "TabIndexFirst"); } }
				public static string TabIndexLast { get { return GetText ("Strings", "Action", "TabIndexLast"); } }
				public static string TabIndexNext { get { return GetText ("Strings", "Action", "TabIndexNext"); } }
				public static string TabIndexPrev { get { return GetText ("Strings", "Action", "TabIndexPrev"); } }
				public static string TabIndexRenum { get { return GetText ("Strings", "Action", "TabIndexRenum"); } }
				public static string ToolEdit { get { return GetText ("Strings", "Action", "ToolEdit"); } }
				public static string ToolGlobal { get { return GetText ("Strings", "Action", "ToolGlobal"); } }
				public static string ToolGrid { get { return GetText ("Strings", "Action", "ToolGrid"); } }
				public static string ToolHand { get { return GetText ("Strings", "Action", "ToolHand"); } }
				public static string ToolSelect { get { return GetText ("Strings", "Action", "ToolSelect"); } }
				public static string ToolZoom { get { return GetText ("Strings", "Action", "ToolZoom"); } }
				public static string Up { get { return GetText ("Strings", "Action", "Up"); } }
			}
			
			public sealed class Application
			{
				public static string Title { get { return GetText ("Strings", "Application", "Title"); } }
			}
			
			public sealed class BundleType
			{
				public static string Captions { get { return GetText ("Strings", "BundleType", "Captions"); } }
				public static string Commands { get { return GetText ("Strings", "BundleType", "Commands"); } }
				public static string Panels { get { return GetText ("Strings", "BundleType", "Panels"); } }
				public static string Scripts { get { return GetText ("Strings", "BundleType", "Scripts"); } }
				public static string Strings { get { return GetText ("Strings", "BundleType", "Strings"); } }
				public static string Types { get { return GetText ("Strings", "BundleType", "Types"); } }
			}
			
			public sealed class Dialog
			{
				public sealed class Button
				{
					public static string Cancel { get { return GetText ("Strings", "Dialog", "Button", "Cancel"); } }
					public static string Close { get { return GetText ("Strings", "Dialog", "Button", "Close"); } }
					public static string Help { get { return GetText ("Strings", "Dialog", "Button", "Help"); } }
					public static string OK { get { return GetText ("Strings", "Dialog", "Button", "OK"); } }
				}
				
				public sealed class DeleteCulture
				{
					public static string Question { get { return GetText ("Strings", "Dialog", "DeleteCulture", "Question"); } }
				}
				
				public sealed class Filter
				{
					public static string Label { get { return GetText ("Strings", "Dialog", "Filter", "Label"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Filter", "Title"); } }
					public sealed class Button
					{
						public static string All { get { return GetText ("Strings", "Dialog", "Filter", "Button", "All"); } }
						public static string Insert { get { return GetText ("Strings", "Dialog", "Filter", "Button", "Insert"); } }
					}
					
					public sealed class Check
					{
						public static string Case { get { return GetText ("Strings", "Dialog", "Filter", "Check", "Case"); } }
						public static string Word { get { return GetText ("Strings", "Dialog", "Filter", "Check", "Word"); } }
					}
					
					public sealed class Radio
					{
						public static string Any { get { return GetText ("Strings", "Dialog", "Filter", "Radio", "Any"); } }
						public static string Begin { get { return GetText ("Strings", "Dialog", "Filter", "Radio", "Begin"); } }
						public static string Jocker { get { return GetText ("Strings", "Dialog", "Filter", "Radio", "Jocker"); } }
					}
				}
				
				public sealed class Glyphs
				{
					public static string Title { get { return GetText ("Strings", "Dialog", "Glyphs", "Title"); } }
					public sealed class Button
					{
						public static string Insert { get { return GetText ("Strings", "Dialog", "Glyphs", "Button", "Insert"); } }
					}
					
					public sealed class Tooltip
					{
						public static string ArraySize { get { return GetText ("Strings", "Dialog", "Glyphs", "Tooltip", "ArraySize"); } }
					}
				}
				
				public sealed class Icon
				{
					public static string None { get { return GetText ("Strings", "Dialog", "Icon", "None"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Icon", "Title"); } }
					public sealed class Button
					{
						public static string Cancel { get { return GetText ("Strings", "Dialog", "Icon", "Button", "Cancel"); } }
						public static string OK { get { return GetText ("Strings", "Dialog", "Icon", "Button", "OK"); } }
					}
					
					public sealed class Filter
					{
						public static string All { get { return GetText ("Strings", "Dialog", "Icon", "Filter", "All"); } }
						public static string One { get { return GetText ("Strings", "Dialog", "Icon", "Filter", "One"); } }
					}
					
					public sealed class Label
					{
						public static string Filter { get { return GetText ("Strings", "Dialog", "Icon", "Label", "Filter"); } }
						public static string Search { get { return GetText ("Strings", "Dialog", "Icon", "Label", "Search"); } }
					}
					
					public sealed class Tooltip
					{
						public static string Mode { get { return GetText ("Strings", "Dialog", "Icon", "Tooltip", "Mode"); } }
						public static string Size { get { return GetText ("Strings", "Dialog", "Icon", "Tooltip", "Size"); } }
					}
				}
				
				public sealed class NewCulture
				{
					public static string Label { get { return GetText ("Strings", "Dialog", "NewCulture", "Label"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "NewCulture", "Title"); } }
					public sealed class Button
					{
						public static string Create { get { return GetText ("Strings", "Dialog", "NewCulture", "Button", "Create"); } }
					}
				}
				
				public sealed class Open
				{
					public static string Label { get { return GetText ("Strings", "Dialog", "Open", "Label"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Open", "Title"); } }
					public sealed class Button
					{
						public static string Open { get { return GetText ("Strings", "Dialog", "Open", "Button", "Open"); } }
					}
				}
				
				public sealed class ResourceSelector
				{
					public static string Label { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Label"); } }
					public static string Text { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Text"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Title"); } }
					public sealed class Button
					{
						public static string Clear { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Button", "Clear"); } }
						public static string Create { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Button", "Create"); } }
						public static string Use { get { return GetText ("Strings", "Dialog", "ResourceSelector", "Button", "Use"); } }
					}
				}
				
				public sealed class Save
				{
					public static string Question1 { get { return GetText ("Strings", "Dialog", "Save", "Question1"); } }
					public static string Question2 { get { return GetText ("Strings", "Dialog", "Save", "Question2"); } }
				}
				
				public sealed class Search
				{
					public static string Label { get { return GetText ("Strings", "Dialog", "Search", "Label"); } }
					public static string Replace { get { return GetText ("Strings", "Dialog", "Search", "Replace"); } }
					public static string Title { get { return GetText ("Strings", "Dialog", "Search", "Title"); } }
					public sealed class Button
					{
						public static string Count { get { return GetText ("Strings", "Dialog", "Search", "Button", "Count"); } }
						public static string Replace { get { return GetText ("Strings", "Dialog", "Search", "Button", "Replace"); } }
						public static string ReplaceAll { get { return GetText ("Strings", "Dialog", "Search", "Button", "ReplaceAll"); } }
						public static string Search { get { return GetText ("Strings", "Dialog", "Search", "Button", "Search"); } }
					}
					
					public sealed class Check
					{
						public static string Case { get { return GetText ("Strings", "Dialog", "Search", "Check", "Case"); } }
						public static string Label { get { return GetText ("Strings", "Dialog", "Search", "Check", "Label"); } }
						public static string PrimaryAbout { get { return GetText ("Strings", "Dialog", "Search", "Check", "PrimaryAbout"); } }
						public static string PrimaryDescription { get { return GetText ("Strings", "Dialog", "Search", "Check", "PrimaryDescription"); } }
						public static string PrimaryLabels { get { return GetText ("Strings", "Dialog", "Search", "Check", "PrimaryLabels"); } }
						public static string PrimaryText { get { return GetText ("Strings", "Dialog", "Search", "Check", "PrimaryText"); } }
						public static string SecondaryAbout { get { return GetText ("Strings", "Dialog", "Search", "Check", "SecondaryAbout"); } }
						public static string SecondaryDescription { get { return GetText ("Strings", "Dialog", "Search", "Check", "SecondaryDescription"); } }
						public static string SecondaryLabels { get { return GetText ("Strings", "Dialog", "Search", "Check", "SecondaryLabels"); } }
						public static string SecondaryText { get { return GetText ("Strings", "Dialog", "Search", "Check", "SecondaryText"); } }
						public static string Who { get { return GetText ("Strings", "Dialog", "Search", "Check", "Who"); } }
						public static string Word { get { return GetText ("Strings", "Dialog", "Search", "Check", "Word"); } }
					}
					
					public sealed class Message
					{
						public static string Count { get { return GetText ("Strings", "Dialog", "Search", "Message", "Count"); } }
						public static string Error { get { return GetText ("Strings", "Dialog", "Search", "Message", "Error"); } }
						public static string Replace { get { return GetText ("Strings", "Dialog", "Search", "Message", "Replace"); } }
					}
				}
				
				public sealed class Tooltip
				{
					public static string Close { get { return GetText ("Strings", "Dialog", "Tooltip", "Close"); } }
					public static string Help { get { return GetText ("Strings", "Dialog", "Tooltip", "Help"); } }
					public static string Resize { get { return GetText ("Strings", "Dialog", "Tooltip", "Resize"); } }
				}
			}
			
			public sealed class Error
			{
				public static string CheckOK { get { return GetText ("Strings", "Error", "CheckOK"); } }
				public static string InvalidLabel { get { return GetText ("Strings", "Error", "InvalidLabel"); } }
				public static string NameAlreadyExist { get { return GetText ("Strings", "Error", "NameAlreadyExist"); } }
				public static string ShortcutMany { get { return GetText ("Strings", "Error", "ShortcutMany"); } }
			}
			
			public sealed class Misc
			{
				public static string Copy { get { return GetText ("Strings", "Misc", "Copy"); } }
				public static string CopyOf { get { return GetText ("Strings", "Misc", "CopyOf"); } }
				public static string Extract { get { return GetText ("Strings", "Misc", "Extract"); } }
				public static string ExtractOf { get { return GetText ("Strings", "Misc", "ExtractOf"); } }
				public static string NoTitle { get { return GetText ("Strings", "Misc", "NoTitle"); } }
			}
			
			public sealed class Ribbon
			{
				public static string Main { get { return GetText ("Strings", "Ribbon", "Main"); } }
				public static string Oper { get { return GetText ("Strings", "Ribbon", "Oper"); } }
				public static string Text { get { return GetText ("Strings", "Ribbon", "Text"); } }
				public sealed class Section
				{
					public static string Access { get { return GetText ("Strings", "Ribbon", "Section", "Access"); } }
					public static string Align { get { return GetText ("Strings", "Ribbon", "Section", "Align"); } }
					public static string Character { get { return GetText ("Strings", "Ribbon", "Section", "Character"); } }
					public static string Clipboard { get { return GetText ("Strings", "Ribbon", "Section", "Clipboard"); } }
					public static string Culture { get { return GetText ("Strings", "Ribbon", "Section", "Culture"); } }
					public static string File { get { return GetText ("Strings", "Ribbon", "Section", "File"); } }
					public static string Move { get { return GetText ("Strings", "Ribbon", "Section", "Move"); } }
					public static string MoveHorizontal { get { return GetText ("Strings", "Ribbon", "Section", "MoveHorizontal"); } }
					public static string MoveVertical { get { return GetText ("Strings", "Ribbon", "Section", "MoveVertical"); } }
					public static string Order { get { return GetText ("Strings", "Ribbon", "Section", "Order"); } }
					public static string PanelSelect { get { return GetText ("Strings", "Ribbon", "Section", "PanelSelect"); } }
					public static string PanelShow { get { return GetText ("Strings", "Ribbon", "Section", "PanelShow"); } }
					public static string Select { get { return GetText ("Strings", "Ribbon", "Section", "Select"); } }
					public static string TabIndex { get { return GetText ("Strings", "Ribbon", "Section", "TabIndex"); } }
				}
			}
			
			public sealed class StringCollection
			{
				public static string Add { get { return GetText ("Strings", "StringCollection", "Add"); } }
				public static string Duplicate { get { return GetText ("Strings", "StringCollection", "Duplicate"); } }
				public static string Next { get { return GetText ("Strings", "StringCollection", "Next"); } }
				public static string Prev { get { return GetText ("Strings", "StringCollection", "Prev"); } }
				public static string Remove { get { return GetText ("Strings", "StringCollection", "Remove"); } }
			}
			
			public sealed class Viewers
			{
				public sealed class Captions
				{
					public sealed class About
					{
						public static string Title { get { return GetText ("Strings", "Viewers", "Captions", "About", "Title"); } }
					}
					
					public sealed class Description
					{
						public static string Short { get { return GetText ("Strings", "Viewers", "Captions", "Description", "Short"); } }
						public static string Title { get { return GetText ("Strings", "Viewers", "Captions", "Description", "Title"); } }
					}
					
					public sealed class Icon
					{
						public static string Title { get { return GetText ("Strings", "Viewers", "Captions", "Icon", "Title"); } }
					}
					
					public sealed class Labels
					{
						public static string Title { get { return GetText ("Strings", "Viewers", "Captions", "Labels", "Title"); } }
					}
				}
				
				public sealed class Commands
				{
					public sealed class Group
					{
						public static string Title { get { return GetText ("Strings", "Viewers", "Commands", "Group", "Title"); } }
					}
					
					public sealed class Shortcut
					{
						public static string Main { get { return GetText ("Strings", "Viewers", "Commands", "Shortcut", "Main"); } }
						public static string Suppl { get { return GetText ("Strings", "Viewers", "Commands", "Shortcut", "Suppl"); } }
						public static string Title { get { return GetText ("Strings", "Viewers", "Commands", "Shortcut", "Title"); } }
					}
					
					public sealed class Statefull
					{
						public static string CheckButton { get { return GetText ("Strings", "Viewers", "Commands", "Statefull", "CheckButton"); } }
						public static string Title { get { return GetText ("Strings", "Viewers", "Commands", "Statefull", "Title"); } }
					}
				}
				
				public sealed class Panels
				{
					public static string Info { get { return GetText ("Strings", "Viewers", "Panels", "Info"); } }
					public static string New { get { return GetText ("Strings", "Viewers", "Panels", "New"); } }
					public static string Rectangle { get { return GetText ("Strings", "Viewers", "Panels", "Rectangle"); } }
					public static string TabCultures { get { return GetText ("Strings", "Viewers", "Panels", "TabCultures"); } }
					public static string TabObjects { get { return GetText ("Strings", "Viewers", "Panels", "TabObjects"); } }
					public static string TabProperties { get { return GetText ("Strings", "Viewers", "Panels", "TabProperties"); } }
				}
				
				public sealed class Strings
				{
					public static string About { get { return GetText ("Strings", "Viewers", "Strings", "About"); } }
					public static string Edit { get { return GetText ("Strings", "Viewers", "Strings", "Edit"); } }
					public static string Reference { get { return GetText ("Strings", "Viewers", "Strings", "Reference"); } }
				}
			}
			
			public static string GetString(params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			
			#region Internal Support Code
			private static string GetText(string bundle, params string[] path)
			{
				string field = string.Join (".", path);
				return _bundle[field].AsString;
			}
			private static Epsitec.Common.Support.ResourceBundle _bundle = _manager.GetBundle ("Strings");
			#endregion
		}
		
		public static void Initialise(System.Type type, string name)
		{
			_manager = new Epsitec.Common.Support.ResourceManager (type);
			_manager.DefineDefaultModuleName (name);
		}
		
		private static Epsitec.Common.Support.ResourceManager _manager = Epsitec.Common.Support.Resources.DefaultManager;
	}
}
