<bundle>
 <class>GroupBox</class>
 <name>my_group</name>
 <size>500;300</size>
 <widgets>				<!-- le champ 'widgets' est constitué par une liste de bundles -->
  <list>				<!-- début de la liste -->
   <bundle>				<!-- premier bundle -->
    <class>CheckButton</class>
   </bundle>
   <bundle>				<!-- second bundle -->
    <class>RadioButton</class>
   </bundle>
   <ref t='button.cancel'/>
  </list>				<!-- fin de la liste -->
 </widgets>
</bundle>
