<bundle>
 <data name='class'>GroupBox</data>
 <data name='name'>my_group</data>
 <data name='size'>500;300</data>
 <list name='widgets'>				<!-- la liste 'widgets' est constitué par une collection de bundles -->
  <bundle>							<!-- premier bundle -->
   <data name='class'>CheckButton</data>
  </bundle>
  <bundle>							<!-- second bundle -->
   <data name='class'>RadioButton</data>
  </bundle>
  <ref target='button.cancel'/>
 </list>							<!-- fin de la liste -->
</bundle>
