//	Automatically generated by ResGenerator, on 07.12.2007
//	Do not edit manually.

namespace Epsitec.App.Dolphin
{
	public static class Res
	{
		
		static Res()
		{
			Res.Initialize (typeof (Res), "App.Dolphin");
		}

		public static void Initialize()
		{
		}

		private static void Initialize(System.Type type, string name)
		{
			Res._manager = new global::Epsitec.Common.Support.ResourceManager (type);
			Res._manager.DefineDefaultModuleName (name);
		}
		
		public static global::Epsitec.Common.Support.ResourceManager Manager
		{
			get { return Res._manager; }
		}
		
		public static int ModuleId
		{
			get { return _moduleId; }
		}
		
		private static global::Epsitec.Common.Support.ResourceManager _manager = global::Epsitec.Common.Support.Resources.DefaultManager;
		private const int _moduleId = 103;
	}
}
