<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="fr">
  <data name="Cap.New" id="0">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Cmd.New" id="01">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Typ.New" id="02">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Val.New" id="03">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Fld.New" id="04">&lt;s:data id="_0" f:Name="New" /&gt;</data>
  <data name="Typ.StructuredType.New" id="05">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="3" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="*aT" /&gt;&lt;s:type id="_3" s:name="*S" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_3" /&gt;&lt;s:data id="_1" f:Name="New" f:_2.ComplexType="{ObjRef _2}" /&gt;&lt;s:data id="_2" f:Fields="{Collection {Text '[6306];&amp;lt;invalid&amp;gt;;0;[6306]'}}" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
  <data name="Fld.New.Champ1" id="06" mod="1">&lt;s:data id="_0" f:Name="Champ1" f:Labels="{Collection {Text 'Champ1'}}" /&gt;</data>
</bundle>