<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="AiderUserDataTitle" id="G002">Données de l&amp;apos;utilisateur</data>
  <data name="AiderUserPasswordTitle" id="G102">Mot de passe</data>
  <data name="AiderUserLoginNameEmpty" id="G202">Le nom d&amp;apos;utilisateur ne peut pas être vide.</data>
  <data name="AiderUserLoginNameDuplicate" id="G302">Ce nom d&amp;apos;utilisateur est déjà utilisé par un autre utilisateur.</data>
  <data name="AiderUserPasswordTooShort" id="G402">Le mot de passe doit faire au moins 8 charactères.</data>
  <data name="AiderUserPasswordMismatch" id="G502">La confirmation du mot de passe ne correspond pas au mot de passe.</data>
</bundle>